In [1]:
import pandas as pd
import numpy as np

from sqlalchemy import create_engine, text

# PostgreSQL connection
engine = create_engine(
    "postgresql+psycopg2://postgres:Lif3suck$@localhost:5432/scm_forecasting"
)

# Extract sales data
query = """
SELECT
    id,
    date,
    store_nbr,
    family,
    sales,
    onpromotion
FROM public.sales
ORDER BY date, store_nbr, family;
"""

sales_df = pd.read_sql(query, engine)

print("Shape:", sales_df.shape)
sales_df.head()

Shape: (3000888, 6)

   id        date  store_nbr      family  sales  onpromotion
0   0  2013-01-01          1  AUTOMOTIVE    0.0            0
1   1  2013-01-01          1   BABY CARE    0.0            0
2   2  2013-01-01          1      BEAUTY    0.0            0
3   3  2013-01-01          1   BEVERAGES    0.0            0
4   4  2013-01-01          1       BOOKS    0.0            0

In [2]:
# Ensure correct date type
sales_df["date"] = pd.to_datetime(sales_df["date"])

# Development combination
DEV_STORE = 1
DEV_FAMILY = "GROCERY I"

dev_df = (
    sales_df[
        (sales_df["store_nbr"] == DEV_STORE) &
        (sales_df["family"] == DEV_FAMILY)
    ]
    .copy()
    .sort_values("date")
    .reset_index(drop=True)
)

print("Shape:", dev_df.shape)
print("Date range:", dev_df["date"].min(), "to", dev_df["date"].max())
print("Missing dates:", 
      pd.date_range(
          dev_df["date"].min(),
          dev_df["date"].max(),
          freq="D"
      ).difference(dev_df["date"]).size
)

dev_df.head()

Shape: (1684, 6)
Date range: 2013-01-01 00:00:00 to 2017-08-15 00:00:00
Missing dates: 4

     id       date  store_nbr     family   sales  onpromotion
0    12 2013-01-01          1  GROCERY I     0.0            0
1  1794 2013-01-02          1  GROCERY I  2652.0            0
2  3576 2013-01-03          1  GROCERY I  2121.0            0
3  5358 2013-01-04          1  GROCERY I  2056.0            0
4  7140 2013-01-05          1  GROCERY I  2216.0            0

In [3]:
# Create complete daily calendar
full_dates = pd.date_range(
    start=dev_df["date"].min(),
    end=dev_df["date"].max(),
    freq="D"
)

# Reindex to continuous daily frequency
dev_df = (
    dev_df
    .set_index("date")
    .reindex(full_dates)
)

# Restore identifying fields
dev_df["store_nbr"] = DEV_STORE
dev_df["family"] = DEV_FAMILY

# Missing calendar days represent zero activity
dev_df["sales"] = dev_df["sales"].fillna(0)
dev_df["onpromotion"] = dev_df["onpromotion"].fillna(0)

# Clean index/column structure
dev_df.index.name = "date"
dev_df = dev_df.reset_index()

print("Shape:", dev_df.shape)
print("Date range:", dev_df["date"].min(), "to", dev_df["date"].max())

print("\nMissing dates after reindex:")
expected_dates = pd.date_range(
    dev_df["date"].min(),
    dev_df["date"].max(),
    freq="D"
)
print(expected_dates.difference(dev_df["date"]))

print("\nNull counts:")
print(dev_df.isnull().sum())

print("\nChristmas rows:")
print(
    dev_df[
        (dev_df["date"].dt.month == 12) &
        (dev_df["date"].dt.day == 25)
    ][["date", "store_nbr", "family", "sales", "onpromotion"]]
)

# ID is not needed for forecasting
dev_df = dev_df.drop(columns=["id"])

print("Final columns:", dev_df.columns.tolist())
print("Null counts:")
print(dev_df.isnull().sum())

Shape: (1688, 6)
Date range: 2013-01-01 00:00:00 to 2017-08-15 00:00:00

Missing dates after reindex:
DatetimeIndex([], dtype='datetime64[s]', freq='D')

Null counts:
date           0
id             4
store_nbr      0
family         0
sales          0
onpromotion    0
dtype: int64

Christmas rows:
           date  store_nbr     family  sales  onpromotion
358  2013-12-25          1  GROCERY I    0.0          0.0
723  2014-12-25          1  GROCERY I    0.0          0.0
1088 2015-12-25          1  GROCERY I    0.0          0.0
1454 2016-12-25          1  GROCERY I    0.0          0.0
Final columns: ['date', 'store_nbr', 'family', 'sales', 'onpromotion']
Null counts:
date           0
store_nbr      0
family         0
sales          0
onpromotion    0
dtype: int64

In [4]:
# Calendar features
dev_df["year"] = dev_df["date"].dt.year
dev_df["month"] = dev_df["date"].dt.month
dev_df["day"] = dev_df["date"].dt.day
dev_df["dayofweek"] = dev_df["date"].dt.dayofweek
dev_df["dayofyear"] = dev_df["date"].dt.dayofyear
dev_df["weekofyear"] = dev_df["date"].dt.isocalendar().week.astype(int)

# Lag features
dev_df["lag_1"] = dev_df["sales"].shift(1)
dev_df["lag_7"] = dev_df["sales"].shift(7)
dev_df["lag_14"] = dev_df["sales"].shift(14)
dev_df["lag_28"] = dev_df["sales"].shift(28)

# Rolling features
dev_df["rolling_mean_7"] = dev_df["sales"].shift(1).rolling(7).mean()
dev_df["rolling_mean_14"] = dev_df["sales"].shift(1).rolling(14).mean()
dev_df["rolling_mean_28"] = dev_df["sales"].shift(1).rolling(28).mean()

print("Shape:", dev_df.shape)
print("\nColumns:")
print(dev_df.columns.tolist())

print("\nNull counts:")
print(dev_df.isnull().sum())

Shape: (1688, 18)

Columns:
['date', 'store_nbr', 'family', 'sales', 'onpromotion', 'year', 'month', 'day', 'dayofweek', 'dayofyear', 'weekofyear', 'lag_1', 'lag_7', 'lag_14', 'lag_28', 'rolling_mean_7', 'rolling_mean_14', 'rolling_mean_28']

Null counts:
date                0
store_nbr           0
family              0
sales               0
onpromotion         0
year                0
month               0
day                 0
dayofweek           0
dayofyear           0
weekofyear          0
lag_1               1
lag_7               7
lag_14             14
lag_28             28
rolling_mean_7      7
rolling_mean_14    14
rolling_mean_28    28
dtype: int64

In [5]:
# Remove rows where lag/rolling features are unavailable
model_df = dev_df.dropna().copy()

print("Original rows:", len(dev_df))
print("Model rows:", len(model_df))

print("\nNull counts:")
print(model_df.isnull().sum())

print("\nDate range:")
print(model_df["date"].min(), "to", model_df["date"].max())

Original rows: 1688
Model rows: 1660

Null counts:
date               0
store_nbr          0
family             0
sales              0
onpromotion        0
year               0
month              0
day                0
dayofweek          0
dayofyear          0
weekofyear         0
lag_1              0
lag_7              0
lag_14             0
lag_28             0
rolling_mean_7     0
rolling_mean_14    0
rolling_mean_28    0
dtype: int64

Date range:
2013-01-29 00:00:00 to 2017-08-15 00:00:00

In [6]:
# Chronological train/test split

TEST_DAYS = 30

train_df = model_df.iloc[:-TEST_DAYS].copy()
test_df = model_df.iloc[-TEST_DAYS:].copy()

print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

print("\nTrain date range:")
print(train_df["date"].min(), "to", train_df["date"].max())

print("\nTest date range:")
print(test_df["date"].min(), "to", test_df["date"].max())

print("\nTrain/Test sales:")
print("Train sales:", train_df["sales"].sum())
print("Test sales:", test_df["sales"].sum())

Train shape: (1630, 18)
Test shape: (30, 18)

Train date range:
2013-01-29 00:00:00 to 2017-07-16 00:00:00

Test date range:
2017-07-17 00:00:00 to 2017-08-15 00:00:00

Train/Test sales:
Train sales: 3623931.0
Test sales: 71723.0

In [7]:
# Baseline 1: Naive forecast
# Tomorrow = yesterday's sales

test_predictions_naive = test_df["lag_1"].values

# Baseline 2: 7-day seasonal naive
# Same weekday as previous week

test_predictions_seasonal = test_df["lag_7"].values

print("Naive predictions:", len(test_predictions_naive))
print("Seasonal naive predictions:", len(test_predictions_seasonal))

print("\nActual test sales:")
print(test_df["sales"].values[:10])

print("\nNaive predictions:")
print(test_predictions_naive[:10])

print("\nSeasonal naive predictions:")
print(test_predictions_seasonal[:10])

Naive predictions: 30
Seasonal naive predictions: 30

Actual test sales:
[2720. 3370. 3065. 2592. 2725. 2576. 1371. 2612. 2405. 2878.]

Naive predictions:
[1028. 2720. 3370. 3065. 2592. 2725. 2576. 1371. 2612. 2405.]

Seasonal naive predictions:
[2849. 2712. 3185. 2571. 3182. 2297. 1028. 2720. 3370. 3065.]

In [8]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

actual = test_df["sales"].values

# Naive metrics
naive_mae = mean_absolute_error(actual, test_predictions_naive)
naive_rmse = np.sqrt(mean_squared_error(actual, test_predictions_naive))

# Seasonal Naive metrics
seasonal_mae = mean_absolute_error(actual, test_predictions_seasonal)
seasonal_rmse = np.sqrt(mean_squared_error(actual, test_predictions_seasonal))

print("=== Naive Baseline ===")
print("MAE :", naive_mae)
print("RMSE:", naive_rmse)

print("\n=== Seasonal Naive Baseline ===")
print("MAE :", seasonal_mae)
print("RMSE:", seasonal_rmse)

=== Naive Baseline ===
MAE : 694.2666666666667
RMSE: 874.114942861254

=== Seasonal Naive Baseline ===
MAE : 341.6333333333333
RMSE: 453.17057127164236

In [9]:
# Features used by XGBoost

feature_cols = [
    "onpromotion",
    "year",
    "month",
    "day",
    "dayofweek",
    "dayofyear",
    "weekofyear",
    "lag_1",
    "lag_7",
    "lag_14",
    "lag_28",
    "rolling_mean_7",
    "rolling_mean_14",
    "rolling_mean_28"
]

X_train = train_df[feature_cols]
y_train = train_df["sales"]

X_test = test_df[feature_cols]
y_test = test_df["sales"]

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

print("\nFeatures:")
print(feature_cols)

print("\nMissing values:")
print("X_train:", X_train.isnull().sum().sum())
print("X_test :", X_test.isnull().sum().sum())

X_train shape: (1630, 14)
y_train shape: (1630,)
X_test shape: (30, 14)
y_test shape: (30,)

Features:
['onpromotion', 'year', 'month', 'day', 'dayofweek', 'dayofyear', 'weekofyear', 'lag_1', 'lag_7', 'lag_14', 'lag_28', 'rolling_mean_7', 'rolling_mean_14', 'rolling_mean_28']

Missing values:
X_train: 0
X_test : 0

In [10]:
from xgboost import XGBRegressor

xgb_model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    random_state=42
)

xgb_model.fit(
    X_train,
    y_train
)

xgb_predictions = xgb_model.predict(X_test)

print("Predictions:", len(xgb_predictions))
print("First 10 predictions:")
print(xgb_predictions[:10])

print("\nPrediction range:")
print("Min:", xgb_predictions.min())
print("Max:", xgb_predictions.max())

Predictions: 30
First 10 predictions:
[2857.474  2829.6099 3235.9905 2790.5093 3133.4888 2849.792  1156.9578
 2760.848  2711.58   2821.3157]

Prediction range:
Min: 972.95593
Max: 3235.9905

In [11]:
# Evaluate XGBoost

xgb_mae = mean_absolute_error(y_test, xgb_predictions)
xgb_rmse = np.sqrt(mean_squared_error(y_test, xgb_predictions))

print("=== XGBoost ===")
print("MAE :", xgb_mae)
print("RMSE:", xgb_rmse)

print("\n=== Comparison ===")
print(f"Naive MAE           : {naive_mae:.4f}")
print(f"Seasonal Naive MAE  : {seasonal_mae:.4f}")
print(f"XGBoost MAE         : {xgb_mae:.4f}")

print(f"\nNaive RMSE          : {naive_rmse:.4f}")
print(f"Seasonal Naive RMSE : {seasonal_rmse:.4f}")
print(f"XGBoost RMSE        : {xgb_rmse:.4f}")

=== XGBoost ===
MAE : 295.0883036295573
RMSE: 388.5083591995155

=== Comparison ===
Naive MAE           : 694.2667
Seasonal Naive MAE  : 341.6333
XGBoost MAE         : 295.0883

Naive RMSE          : 874.1149
Seasonal Naive RMSE : 453.1706
XGBoost RMSE        : 388.5084

In [12]:
comparison_df = pd.DataFrame({
    "date": test_df["date"].values,
    "actual_sales": y_test.values,
    "predicted_sales": xgb_predictions
})

comparison_df["error"] = (
    comparison_df["actual_sales"] -
    comparison_df["predicted_sales"]
)

comparison_df["absolute_error"] = comparison_df["error"].abs()

print(comparison_df.to_string(index=False))

print("\nAverage Actual Sales:",
      comparison_df["actual_sales"].mean())

print("Average Predicted Sales:",
      comparison_df["predicted_sales"].mean())

print("Total Actual Sales:",
      comparison_df["actual_sales"].sum())

print("Total Predicted Sales:",
      comparison_df["predicted_sales"].sum())

      date  actual_sales  predicted_sales        error  absolute_error
2017-07-17        2720.0      2857.474121  -137.474121      137.474121
2017-07-18        3370.0      2829.609863   540.390137      540.390137
2017-07-19        3065.0      3235.990479  -170.990479      170.990479
2017-07-20        2592.0      2790.509277  -198.509277      198.509277
2017-07-21        2725.0      3133.488770  -408.488770      408.488770
2017-07-22        2576.0      2849.791992  -273.791992      273.791992
2017-07-23        1371.0      1156.957764   214.042236      214.042236
2017-07-24        2612.0      2760.847900  -148.847900      148.847900
2017-07-25        2405.0      2711.580078  -306.580078      306.580078
2017-07-26        2878.0      2821.315674    56.684326       56.684326
2017-07-27        2466.0      2175.012207   290.987793      290.987793
2017-07-28        2622.0      2287.189941   334.810059      334.810059
2017-07-29        2446.0      2425.473389    20.526611       20.526611
2017-07-30        1086.0      1017.796326    68.203674       68.203674
2017-07-31        2966.0      2180.155029   785.844971      785.844971
2017-08-01        2872.0      2908.706299   -36.706299       36.706299
2017-08-02        3247.0      3037.448975   209.551025      209.551025
2017-08-03        2177.0      2764.377441  -587.377441      587.377441
2017-08-04        2778.0      2821.593262   -43.593262       43.593262
2017-08-05        2034.0      2686.451172  -652.451172      652.451172
2017-08-06        1025.0      1143.966797  -118.966797      118.966797
2017-08-07        2551.0      2587.805908   -36.805908       36.805908
2017-08-08        3062.0      2526.755371   535.244629      535.244629
2017-08-09        2719.0      2656.336914    62.663086       62.663086
2017-08-10        2591.0      2213.726562   377.273438      377.273438
2017-08-11        1270.0      2320.807861 -1050.807861     1050.807861
2017-08-12        1630.0      2261.604492  -631.604492      631.604492
2017-08-13         952.0       972.955933   -20.955933       20.955933
2017-08-14        2407.0      2599.904785  -192.904785      192.904785
2017-08-15        2508.0      2847.570557  -339.570557      339.570557

Average Actual Sales: 2390.766666666667
Average Predicted Sales: 2452.7734
Total Actual Sales: 71723.0
Total Predicted Sales: 73583.2

In [13]:
# Final model trained on all available historical data

X_full = model_df[feature_cols]
y_full = model_df["sales"]

final_model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    random_state=42
)

final_model.fit(
    X_full,
    y_full
)

print("Final training rows:", len(X_full))
print("Final features:", X_full.shape[1])
print("Final model trained successfully.")

Final training rows: 1660
Final features: 14
Final model trained successfully.

In [14]:
# Recursive 30-day forecast

forecast_days = 30

history = model_df[["date", "sales", "onpromotion"]].copy()

future_dates = pd.date_range(
    start=history["date"].max() + pd.Timedelta(days=1),
    periods=forecast_days,
    freq="D"
)

future_predictions = []

for forecast_date in future_dates:

    temp = history.copy()

    # Calendar features
    year = forecast_date.year
    month = forecast_date.month
    day = forecast_date.day
    dayofweek = forecast_date.dayofweek
    dayofyear = forecast_date.dayofyear
    weekofyear = forecast_date.isocalendar().week

    # Lag features
    lag_1 = temp["sales"].iloc[-1]
    lag_7 = temp["sales"].iloc[-7]
    lag_14 = temp["sales"].iloc[-14]
    lag_28 = temp["sales"].iloc[-28:]

    # Rolling features
    rolling_mean_7 = temp["sales"].iloc[-7:].mean()
    rolling_mean_14 = temp["sales"].iloc[-14:].mean()
    rolling_mean_28 = temp["sales"].iloc[-28:].mean()

    # Future promotion is unknown, so use 0
    onpromotion = 0

    X_future = pd.DataFrame([{
        "onpromotion": onpromotion,
        "year": year,
        "month": month,
        "day": day,
        "dayofweek": dayofweek,
        "dayofyear": dayofyear,
        "weekofyear": int(weekofyear),
        "lag_1": lag_1,
        "lag_7": lag_7,
        "lag_14": lag_14,
        "lag_28": lag_28.iloc[-1],
        "rolling_mean_7": rolling_mean_7,
        "rolling_mean_14": rolling_mean_14,
        "rolling_mean_28": rolling_mean_28
    }])

    prediction = final_model.predict(X_future)[0]

    # Sales cannot be negative
    prediction = max(0, prediction)

    future_predictions.append(prediction)

    # Add prediction to history for recursive forecasting
    history = pd.concat([
        history,
        pd.DataFrame([{
            "date": forecast_date,
            "sales": prediction,
            "onpromotion": onpromotion
        }])
    ], ignore_index=True)

forecast_df = pd.DataFrame({
    "forecast_date": future_dates,
    "predicted_sales": future_predictions
})

print("Forecast rows:", len(forecast_df))
print("\nForecast range:")
print(
    forecast_df["forecast_date"].min(),
    "to",
    forecast_df["forecast_date"].max()
)

print("\nForecast summary:")
print(forecast_df["predicted_sales"].describe())

print("\nForecast:")
print(forecast_df.to_string(index=False))

Forecast rows: 30

Forecast range:
2017-08-16 00:00:00 to 2017-09-14 00:00:00

Forecast summary:
count      30.000000
mean     2074.742676
std       422.483948
min      1004.832947
25%      2017.065948
50%      2147.919800
75%      2254.355164
max      2752.681885
Name: predicted_sales, dtype: float64

Forecast:
forecast_date  predicted_sales
   2017-08-16      2489.611816
   2017-08-17      2135.165527
   2017-08-18      2017.798828
   2017-08-19      1985.974731
   2017-08-20      1038.613647
   2017-08-21      2032.479126
   2017-08-22      2255.258789
   2017-08-23      2424.612793
   2017-08-24      2093.099365
   2017-08-25      1935.908569
   2017-08-26      1808.475952
   2017-08-27      1004.832947
   2017-08-28      2162.013672
   2017-08-29      2154.392822
   2017-08-30      2557.573975
   2017-08-31      2094.897217
   2017-09-01      2230.776611
   2017-09-02      2251.644287
   2017-09-03      1451.574341
   2017-09-04      2462.396484
   2017-09-05      2484.059570
   2017-09-06      2752.681885
   2017-09-07      2220.398438
   2017-09-08      2141.446777
   2017-09-09      2016.821655
   2017-09-10      1132.811890
   2017-09-11      2125.483887
   2017-09-12      2208.967041
   2017-09-13      2405.897705
   2017-09-14      2166.608398

In [15]:
# Validate final forecast

print("Rows:", len(forecast_df))
print("Null predictions:", forecast_df["predicted_sales"].isnull().sum())
print("Negative predictions:", (forecast_df["predicted_sales"] < 0).sum())

print("\nTotal 30-day forecast:",
      forecast_df["predicted_sales"].sum())

print("Average daily forecast:",
      forecast_df["predicted_sales"].mean())

print("\nFirst 5 days:")
print(forecast_df.head())

print("\nLast 5 days:")
print(forecast_df.tail())

Rows: 30
Null predictions: 0
Negative predictions: 0

Total 30-day forecast: 62242.28
Average daily forecast: 2074.7427

First 5 days:
  forecast_date  predicted_sales
0    2017-08-16      2489.611816
1    2017-08-17      2135.165527
2    2017-08-18      2017.798828
3    2017-08-19      1985.974731
4    2017-08-20      1038.613647

Last 5 days:
   forecast_date  predicted_sales
25    2017-09-10      1132.811890
26    2017-09-11      2125.483887
27    2017-09-12      2208.967041
28    2017-09-13      2405.897705
29    2017-09-14      2166.608398

In [16]:
# Inventory planning parameters

LEAD_TIME_DAYS = 7
SERVICE_LEVEL_Z = 1.65

# Forecast-based demand statistics
daily_forecast_mean = forecast_df["predicted_sales"].mean()
daily_forecast_std = forecast_df["predicted_sales"].std()

# Lead-time demand
lead_time_demand = daily_forecast_mean * LEAD_TIME_DAYS

# Safety stock
safety_stock = SERVICE_LEVEL_Z * daily_forecast_std * np.sqrt(LEAD_TIME_DAYS)

# Reorder point
reorder_point = lead_time_demand + safety_stock

print("Daily Forecast Mean:", daily_forecast_mean)
print("Daily Forecast Std :", daily_forecast_std)

print("\nLead Time:", LEAD_TIME_DAYS, "days")
print("Lead-Time Demand:", lead_time_demand)
print("Safety Stock:", safety_stock)
print("Reorder Point:", reorder_point)

Daily Forecast Mean: 2074.7427
Daily Forecast Std : 422.48395

Lead Time: 7 days
Lead-Time Demand: 14523.199
Safety Stock: 1844.3492987373163
Reorder Point: 16367.548517487316

In [17]:
# EOQ annual demand
# Exclude incomplete 2017 data

complete_years = [2013, 2014, 2015, 2016]

annual_demand = (
    model_df[
        model_df["date"].dt.year.isin(complete_years)
    ]
    .groupby(model_df["date"].dt.year)["sales"]
    .sum()
)

average_annual_demand = annual_demand.mean()

print("Complete-year historical demand:")
print(annual_demand)

print("\nAverage Annual Demand:", average_annual_demand)

Complete-year historical demand:
date
2013    627472.0
2014    741844.0
2015    813668.0
2016    919204.0
Name: sales, dtype: float64

Average Annual Demand: 775547.0

In [18]:
# ==============================
# EOQ CALCULATION
# ==============================

annual_demand_eoq = average_annual_demand

ordering_cost = 500
holding_cost = 10

eoq = np.sqrt(
    (2 * annual_demand_eoq * ordering_cost)
    / holding_cost
)

print("Annual Demand:", annual_demand_eoq)
print("Ordering Cost per Order: ₹", ordering_cost)
print("Annual Holding Cost per Unit: ₹", holding_cost)
print("EOQ:", round(eoq, 2))

Annual Demand: 775547.0
Ordering Cost per Order: ₹ 500
Annual Holding Cost per Unit: ₹ 10
EOQ: 8806.51

In [19]:
# ==============================
# INVENTORY PLAN
# ==============================

inventory_plan_df = pd.DataFrame([{
    "store_nbr": DEV_STORE,
    "family": DEV_FAMILY,
    "lead_time_days": LEAD_TIME_DAYS,
    "lead_time_demand": lead_time_demand,
    "safety_stock": safety_stock,
    "reorder_point": reorder_point,
    "eoq": eoq
}])

print(inventory_plan_df.to_string(index=False))

 store_nbr    family  lead_time_days  lead_time_demand  safety_stock  reorder_point         eoq
         1 GROCERY I               7      14523.199219   1844.349299   16367.548517 8806.514634

In [20]:
print("\nValidation:")
print("Rows:", len(inventory_plan_df))
print("Null values:", inventory_plan_df.isnull().sum().sum())
print("Negative values:",
      (inventory_plan_df[
          ["lead_time_demand", "safety_stock", "reorder_point", "eoq"]
      ] < 0).sum().sum())

Validation:
Rows: 1
Null values: 0
Negative values: 0

In [21]:
# ==============================
# CREATE PIPELINE RUN
# ==============================

data_cutoff_date = model_df["date"].max()
forecast_start_date = forecast_df["forecast_date"].min()
forecast_end_date = forecast_df["forecast_date"].max()

model_name = "XGBoost"
model_version = "v2"

run_insert_sql = text("""
    INSERT INTO pipeline_runs (
        data_cutoff_date,
        forecast_start_date,
        forecast_end_date,
        model_name,
        model_version
    )
    VALUES (
        :data_cutoff_date,
        :forecast_start_date,
        :forecast_end_date,
        :model_name,
        :model_version
    )
    RETURNING run_id;
""")

with engine.begin() as conn:
    run_id = conn.execute(
        run_insert_sql,
        {
            "data_cutoff_date": data_cutoff_date,
            "forecast_start_date": forecast_start_date,
            "forecast_end_date": forecast_end_date,
            "model_name": model_name,
            "model_version": model_version
        }
    ).scalar()

print("Created run_id:", run_id)
print("Data cutoff:", data_cutoff_date)
print("Forecast period:", forecast_start_date, "to", forecast_end_date)
print("Model:", model_name, model_version)

Created run_id: 1
Data cutoff: 2017-08-15 00:00:00
Forecast period: 2017-08-16 00:00:00 to 2017-09-14 00:00:00
Model: XGBoost v2

In [22]:
# ==============================
# WRITE FORECAST TO SQL
# ==============================

forecast_to_sql = forecast_df.copy()

forecast_to_sql["run_id"] = run_id
forecast_to_sql["store_nbr"] = DEV_STORE
forecast_to_sql["family"] = DEV_FAMILY

forecast_to_sql = forecast_to_sql[
    [
        "run_id",
        "forecast_date",
        "store_nbr",
        "family",
        "predicted_sales"
    ]
]

forecast_to_sql.to_sql(
    "forecast",
    engine,
    schema="public",
    if_exists="append",
    index=False,
    method="multi"
)

print("Forecast rows written:", len(forecast_to_sql))
print("\nFirst 5 rows:")
print(forecast_to_sql.head())

Forecast rows written: 30

First 5 rows:
   run_id forecast_date  store_nbr     family  predicted_sales
0       1    2017-08-16          1  GROCERY I      2489.611816
1       1    2017-08-17          1  GROCERY I      2135.165527
2       1    2017-08-18          1  GROCERY I      2017.798828
3       1    2017-08-19          1  GROCERY I      1985.974731
4       1    2017-08-20          1  GROCERY I      1038.613647

In [23]:
# ==============================
# FORECAST METRICS
# ==============================

mae = mean_absolute_error(y_test, xgb_predictions)
rmse = np.sqrt(mean_squared_error(y_test, xgb_predictions))

# MAE percentage based on average actual sales
mae_pct = (mae / y_test.mean()) * 100

metrics_df = pd.DataFrame([{
    "run_id": run_id,
    "store_nbr": DEV_STORE,
    "family": DEV_FAMILY,
    "mae": mae,
    "rmse": rmse,
    "mae_pct": mae_pct
}])

print(metrics_df.to_string(index=False))

 run_id  store_nbr    family        mae       rmse   mae_pct
      1          1 GROCERY I 295.088304 388.508359 12.342832

In [24]:
# ==============================
# VALIDATE METRICS
# ==============================

print("Rows:", len(metrics_df))
print("Null values:", metrics_df.isnull().sum().sum())
print("Negative metrics:",
      (metrics_df[["mae", "rmse", "mae_pct"]] < 0).sum().sum())

Rows: 1
Null values: 0
Negative metrics: 0

In [25]:
# ==============================
# WRITE FORECAST METRICS TO SQL
# ==============================

metrics_df.to_sql(
    "forecast_metrics",
    engine,
    schema="public",
    if_exists="append",
    index=False,
    method="multi"
)

print("Metrics rows written:", len(metrics_df))

Metrics rows written: 1

In [26]:
# ==============================
# VALIDATE METRICS IN SQL
# ==============================

check_metrics = pd.read_sql(
    text("""
        SELECT
            run_id,
            store_nbr,
            family,
            mae,
            rmse,
            mae_pct
        FROM public.forecast_metrics
        WHERE run_id = :run_id;
    """),
    engine,
    params={"run_id": run_id}
)

print(check_metrics.to_string(index=False))
print("\nRows in SQL:", len(check_metrics))

 run_id  store_nbr    family        mae       rmse   mae_pct
      1          1 GROCERY I 295.088304 388.508359 12.342832

Rows in SQL: 1

In [27]:
inventory_to_sql = inventory_plan_df.copy()

inventory_to_sql["run_id"] = run_id

inventory_to_sql = inventory_to_sql[
    [
        "run_id",
        "store_nbr",
        "family",
        "lead_time_days",
        "lead_time_demand",
        "safety_stock",
        "reorder_point",
        "eoq"
    ]
]

inventory_to_sql.to_sql(
    "inventory_plan",
    engine,
    schema="public",
    if_exists="append",
    index=False,
    method="multi"
)

print("Inventory rows written:", len(inventory_to_sql))

Inventory rows written: 1

In [28]:
check_inventory = pd.read_sql(
    text("""
        SELECT
            run_id,
            store_nbr,
            family,
            lead_time_days,
            lead_time_demand,
            safety_stock,
            reorder_point,
            eoq
        FROM public.inventory_plan
        WHERE run_id = :run_id;
    """),
    engine,
    params={"run_id": run_id}
)

print(check_inventory.to_string(index=False))
print("\nRows in SQL:", len(check_inventory))

 run_id  store_nbr    family  lead_time_days  lead_time_demand  safety_stock  reorder_point         eoq
      1          1 GROCERY I               7      14523.199219   1844.349299   16367.548517 8806.514634

Rows in SQL: 1

In [29]:
final_validation = pd.read_sql(
    text("""
        SELECT
            pr.run_id,
            pr.data_cutoff_date,
            pr.forecast_start_date,
            pr.forecast_end_date,
            pr.model_name,
            pr.model_version,

            COUNT(DISTINCT f.forecast_id) AS forecast_rows,
            COUNT(DISTINCT fm.metric_id) AS metric_rows,
            COUNT(DISTINCT ip.inventory_plan_id) AS inventory_rows,

            MIN(f.forecast_date) AS actual_forecast_min,
            MAX(f.forecast_date) AS actual_forecast_max

        FROM public.pipeline_runs pr

        LEFT JOIN public.forecast f
            ON pr.run_id = f.run_id

        LEFT JOIN public.forecast_metrics fm
            ON pr.run_id = fm.run_id

        LEFT JOIN public.inventory_plan ip
            ON pr.run_id = ip.run_id

        WHERE pr.run_id = :run_id

        GROUP BY
            pr.run_id,
            pr.data_cutoff_date,
            pr.forecast_start_date,
            pr.forecast_end_date,
            pr.model_name,
            pr.model_version;
    """),
    engine,
    params={"run_id": run_id}
)

print(final_validation.to_string(index=False))

 run_id data_cutoff_date forecast_start_date forecast_end_date model_name model_version  forecast_rows  metric_rows  inventory_rows actual_forecast_min actual_forecast_max
      1       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1          2017-08-16          2017-09-14

In [30]:
# Development scope
DEV_STORES = [1, 2, 3, 4, 5]

DEV_FAMILIES = [
    "BEVERAGES",
    "CLEANING",
    "DAIRY",
    "GROCERY I",
    "PRODUCE"
]

DEV_COMBINATIONS = [
    (store, family)
    for store in DEV_STORES
    for family in DEV_FAMILIES
]

print("Stores:", DEV_STORES)
print("Families:", DEV_FAMILIES)
print("Total combinations:", len(DEV_COMBINATIONS))
print("\nFirst 5 combinations:")
print(DEV_COMBINATIONS[:5])

Stores: [1, 2, 3, 4, 5]
Families: ['BEVERAGES', 'CLEANING', 'DAIRY', 'GROCERY I', 'PRODUCE']
Total combinations: 25

First 5 combinations:
[(1, 'BEVERAGES'), (1, 'CLEANING'), (1, 'DAIRY'), (1, 'GROCERY I'), (1, 'PRODUCE')]

In [31]:
def prepare_store_family_data(sales_df, store_nbr, family):
    """
    Extract one Store × Family series, make the daily date range continuous,
    fill missing sales/promotion values, and create forecasting features.
    """

    df = (
        sales_df[
            (sales_df["store_nbr"] == store_nbr) &
            (sales_df["family"] == family)
        ]
        .copy()
        .sort_values("date")
        .reset_index(drop=True)
    )

    if df.empty:
        raise ValueError(
            f"No data found for Store {store_nbr}, Family '{family}'"
        )

    full_dates = pd.date_range(
        start=df["date"].min(),
        end=df["date"].max(),
        freq="D"
    )

    df = (
        df
        .set_index("date")
        .reindex(full_dates)
    )

    df["store_nbr"] = store_nbr
    df["family"] = family

    df["sales"] = df["sales"].fillna(0)
    df["onpromotion"] = df["onpromotion"].fillna(0)

    df.index.name = "date"
    df = df.reset_index()

    # Remove SQL surrogate ID
    if "id" in df.columns:
        df = df.drop(columns=["id"])

    # Calendar features
    df["year"] = df["date"].dt.year
    df["month"] = df["date"].dt.month
    df["day"] = df["date"].dt.day
    df["dayofweek"] = df["date"].dt.dayofweek
    df["dayofyear"] = df["date"].dt.dayofyear
    df["weekofyear"] = df["date"].dt.isocalendar().week.astype(int)

    # Lag features
    df["lag_1"] = df["sales"].shift(1)
    df["lag_7"] = df["sales"].shift(7)
    df["lag_14"] = df["sales"].shift(14)
    df["lag_28"] = df["sales"].shift(28)

    # Rolling features
    df["rolling_mean_7"] = df["sales"].shift(1).rolling(7).mean()
    df["rolling_mean_14"] = df["sales"].shift(1).rolling(14).mean()
    df["rolling_mean_28"] = df["sales"].shift(1).rolling(28).mean()

    model_df = df.dropna().copy()

    return df, model_df

In [32]:
test_raw_df, test_model_df = prepare_store_family_data(
    sales_df,
    1,
    "GROCERY I"
)

print("Raw series shape:", test_raw_df.shape)
print("Model series shape:", test_model_df.shape)
print("Date range:", test_raw_df["date"].min(), "to", test_raw_df["date"].max())
print("Missing values:", test_model_df.isnull().sum().sum())
print("Feature columns:", len(test_model_df.columns))

Raw series shape: (1688, 18)
Model series shape: (1660, 18)
Date range: 2013-01-01 00:00:00 to 2017-08-15 00:00:00
Missing values: 0
Feature columns: 18

In [33]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
from xgboost import XGBRegressor

FEATURE_COLS = [
    "onpromotion",
    "year",
    "month",
    "day",
    "dayofweek",
    "dayofyear",
    "weekofyear",
    "lag_1",
    "lag_7",
    "lag_14",
    "lag_28",
    "rolling_mean_7",
    "rolling_mean_14",
    "rolling_mean_28"
]

TEST_DAYS = 30


def train_and_evaluate(model_df):
    """
    Train and evaluate XGBoost on the final 30 days
    of a Store × Family time series.
    """

    train_df = model_df.iloc[:-TEST_DAYS].copy()
    test_df = model_df.iloc[-TEST_DAYS:].copy()

    X_train = train_df[FEATURE_COLS]
    y_train = train_df["sales"]

    X_test = test_df[FEATURE_COLS]
    y_test = test_df["sales"]

    # Baselines
    naive_predictions = test_df["lag_1"].values
    seasonal_predictions = test_df["lag_7"].values

    naive_mae = mean_absolute_error(
        y_test,
        naive_predictions
    )

    naive_rmse = np.sqrt(
        mean_squared_error(y_test, naive_predictions)
    )

    seasonal_mae = mean_absolute_error(
        y_test,
        seasonal_predictions
    )

    seasonal_rmse = np.sqrt(
        mean_squared_error(y_test, seasonal_predictions)
    )

    # XGBoost
    model = XGBRegressor(
        n_estimators=500,
        learning_rate=0.05,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        objective="reg:squarederror",
        random_state=42
    )

    model.fit(X_train, y_train)

    predictions = model.predict(X_test)

    mae = mean_absolute_error(
        y_test,
        predictions
    )

    rmse = np.sqrt(
        mean_squared_error(y_test, predictions)
    )

    mae_pct = (mae / y_test.mean()) * 100

    metrics = {
        "mae": mae,
        "rmse": rmse,
        "mae_pct": mae_pct,
        "naive_mae": naive_mae,
        "naive_rmse": naive_rmse,
        "seasonal_mae": seasonal_mae,
        "seasonal_rmse": seasonal_rmse
    }

    return model, train_df, test_df, predictions, metrics

In [34]:
test_model, test_train_df, test_test_df, test_predictions, test_metrics = (
    train_and_evaluate(test_model_df)
)

print("Train rows:", len(test_train_df))
print("Test rows:", len(test_test_df))

print("\nXGBoost:")
print("MAE:", round(test_metrics["mae"], 4))
print("RMSE:", round(test_metrics["rmse"], 4))
print("MAE %:", round(test_metrics["mae_pct"], 4))

print("\nSeasonal Naive:")
print("MAE:", round(test_metrics["seasonal_mae"], 4))
print("RMSE:", round(test_metrics["seasonal_rmse"], 4))

print("\nNaive:")
print("MAE:", round(test_metrics["naive_mae"], 4))
print("RMSE:", round(test_metrics["naive_rmse"], 4))

Train rows: 1630
Test rows: 30

XGBoost:
MAE: 295.0883
RMSE: 388.5084
MAE %: 12.3428

Seasonal Naive:
MAE: 341.6333
RMSE: 453.1706

Naive:
MAE: 694.2667
RMSE: 874.1149

In [35]:
def generate_30_day_forecast(model, model_df):
    """
    Train-independent recursive 30-day forecast.
    Uses the supplied trained model and the latest historical series.
    Future onpromotion is assumed to be 0.
    """

    history = model_df[
        ["date", "sales", "onpromotion"]
    ].copy()

    future_dates = pd.date_range(
        start=history["date"].max() + pd.Timedelta(days=1),
        periods=30,
        freq="D"
    )

    future_predictions = []

    for forecast_date in future_dates:

        lag_1 = history["sales"].iloc[-1]
        lag_7 = history["sales"].iloc[-7]
        lag_14 = history["sales"].iloc[-14]
        lag_28 = history["sales"].iloc[-28]

        rolling_mean_7 = history["sales"].iloc[-7:].mean()
        rolling_mean_14 = history["sales"].iloc[-14:].mean()
        rolling_mean_28 = history["sales"].iloc[-28:].mean()

        onpromotion = 0

        X_future = pd.DataFrame([{
            "onpromotion": onpromotion,
            "year": forecast_date.year,
            "month": forecast_date.month,
            "day": forecast_date.day,
            "dayofweek": forecast_date.dayofweek,
            "dayofyear": forecast_date.dayofyear,
            "weekofyear": int(forecast_date.isocalendar().week),
            "lag_1": lag_1,
            "lag_7": lag_7,
            "lag_14": lag_14,
            "lag_28": lag_28,
            "rolling_mean_7": rolling_mean_7,
            "rolling_mean_14": rolling_mean_14,
            "rolling_mean_28": rolling_mean_28
        }])

        prediction = model.predict(X_future)[0]

        prediction = max(0, prediction)

        future_predictions.append(prediction)

        history = pd.concat(
            [
                history,
                pd.DataFrame([{
                    "date": forecast_date,
                    "sales": prediction,
                    "onpromotion": onpromotion
                }])
            ],
            ignore_index=True
        )

    forecast_df = pd.DataFrame({
        "forecast_date": future_dates,
        "predicted_sales": future_predictions
    })

    return forecast_df

In [36]:
def train_final_model(model_df):
    """
    Train the final XGBoost model using all available
    historical model-ready observations.
    """

    X_full = model_df[FEATURE_COLS]
    y_full = model_df["sales"]

    model = XGBRegressor(
        n_estimators=500,
        learning_rate=0.05,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        objective="reg:squarederror",
        random_state=42
    )

    model.fit(X_full, y_full)

    return model

In [37]:
final_test_model = train_final_model(test_model_df)

test_forecast_df = generate_30_day_forecast(
    final_test_model,
    test_model_df
)

print("Forecast rows:", len(test_forecast_df))
print(
    "Forecast range:",
    test_forecast_df["forecast_date"].min(),
    "to",
    test_forecast_df["forecast_date"].max()
)

print(
    "Total forecast:",
    round(test_forecast_df["predicted_sales"].sum(), 2)
)

print(
    "Average daily forecast:",
    round(test_forecast_df["predicted_sales"].mean(), 2)
)

print(
    "Negative predictions:",
    (test_forecast_df["predicted_sales"] < 0).sum()
)

print("\nFirst 5 rows:")
print(test_forecast_df.head())

Forecast rows: 30
Forecast range: 2017-08-16 00:00:00 to 2017-09-14 00:00:00
Total forecast: 63852.74
Average daily forecast: 2128.42
Negative predictions: 0

First 5 rows:
  forecast_date  predicted_sales
0    2017-08-16      2469.128906
1    2017-08-17      2179.654297
2    2017-08-18      2338.447266
3    2017-08-19      2206.261719
4    2017-08-20       971.245972

In [38]:
# Compare the old validated final model with the new reusable final model

print("Training rows - old model:", len(model_df))
print("Training rows - new model:", len(test_model_df))

print(
    "Same training data:",
    model_df[FEATURE_COLS + ["sales"]].reset_index(drop=True).equals(
        test_model_df[FEATURE_COLS + ["sales"]].reset_index(drop=True)
    )
)

old_pred = final_model.predict(
    test_model_df[FEATURE_COLS]
)

new_pred = final_test_model.predict(
    test_model_df[FEATURE_COLS]
)

comparison_models = pd.DataFrame({
    "old_model_prediction": old_pred,
    "new_model_prediction": new_pred
})

comparison_models["difference"] = (
    comparison_models["old_model_prediction"]
    - comparison_models["new_model_prediction"]
)

print("\nPrediction comparison:")
print(comparison_models.head(10).to_string(index=False))

print("\nMaximum absolute difference:",
      comparison_models["difference"].abs().max())

print("Mean absolute difference:",
      comparison_models["difference"].abs().mean())

Training rows - old model: 1660
Training rows - new model: 1660
Same training data: True

Prediction comparison:
 old_model_prediction  new_model_prediction  difference
          1589.292847           1589.292847         0.0
          2147.178467           2147.178467         0.0
          1519.556641           1519.556641         0.0
          1831.791504           1831.791504         0.0
          2078.988281           2078.988281         0.0
           793.756775            793.756775         0.0
          2211.356689           2211.356689         0.0
          1857.462769           1857.462769         0.0
          2072.888184           2072.888184         0.0
          1530.546631           1530.546631         0.0

Maximum absolute difference: 0.0
Mean absolute difference: 0.0

In [39]:
# Compare the first forecast day's feature inputs
# between the old and reusable approaches.

forecast_date = model_df["date"].max() + pd.Timedelta(days=1)

old_history = model_df[
    ["date", "sales", "onpromotion"]
].copy()

new_history = test_model_df[
    ["date", "sales", "onpromotion"]
].copy()

def build_debug_features(history, forecast_date):
    return pd.DataFrame([{
        "onpromotion": 0,
        "year": forecast_date.year,
        "month": forecast_date.month,
        "day": forecast_date.day,
        "dayofweek": forecast_date.dayofweek,
        "dayofyear": forecast_date.dayofyear,
        "weekofyear": int(forecast_date.isocalendar().week),
        "lag_1": history["sales"].iloc[-1],
        "lag_7": history["sales"].iloc[-7],
        "lag_14": history["sales"].iloc[-14],
        "lag_28": history["sales"].iloc[-28],
        "rolling_mean_7": history["sales"].iloc[-7:].mean(),
        "rolling_mean_14": history["sales"].iloc[-14:].mean(),
        "rolling_mean_28": history["sales"].iloc[-28:].mean()
    }])

old_features = build_debug_features(old_history, forecast_date)
new_features = build_debug_features(new_history, forecast_date)

print("Feature inputs identical:",
      old_features.equals(new_features))

print("\nFeature comparison:")
print(
    pd.DataFrame({
        "old": old_features.iloc[0],
        "new": new_features.iloc[0],
        "difference": (
            old_features.iloc[0] -
            new_features.iloc[0]
        )
    }).to_string()
)

Feature inputs identical: True

Feature comparison:
                         old          new  difference
onpromotion         0.000000     0.000000         0.0
year             2017.000000  2017.000000         0.0
month               8.000000     8.000000         0.0
day                16.000000    16.000000         0.0
dayofweek           2.000000     2.000000         0.0
dayofyear         228.000000   228.000000         0.0
weekofyear         33.000000    33.000000         0.0
lag_1            2508.000000  2508.000000         0.0
lag_7            2719.000000  2719.000000         0.0
lag_14           3247.000000  3247.000000         0.0
lag_28           3065.000000  3065.000000         0.0
rolling_mean_7   2011.000000  2011.000000         0.0
rolling_mean_14  2210.785714  2210.785714         0.0
rolling_mean_28  2344.035714  2344.035714         0.0

In [40]:
# Compare the original validated recursive forecast
# against the reusable forecast, day by day.

old_history = model_df[
    ["date", "sales", "onpromotion"]
].copy()

old_future_dates = pd.date_range(
    start=old_history["date"].max() + pd.Timedelta(days=1),
    periods=30,
    freq="D"
)

old_predictions = []

for forecast_date in old_future_dates:

    temp = old_history.copy()

    X_future = pd.DataFrame([{
        "onpromotion": 0,
        "year": forecast_date.year,
        "month": forecast_date.month,
        "day": forecast_date.day,
        "dayofweek": forecast_date.dayofweek,
        "dayofyear": forecast_date.dayofyear,
        "weekofyear": int(forecast_date.isocalendar().week),

        "lag_1": temp["sales"].iloc[-1],
        "lag_7": temp["sales"].iloc[-7],
        "lag_14": temp["sales"].iloc[-14],
        "lag_28": temp["sales"].iloc[-28],

        "rolling_mean_7": temp["sales"].iloc[-7:].mean(),
        "rolling_mean_14": temp["sales"].iloc[-14:].mean(),
        "rolling_mean_28": temp["sales"].iloc[-28:].mean()
    }])

    prediction = final_model.predict(X_future)[0]
    prediction = max(0, prediction)

    old_predictions.append(prediction)

    old_history = pd.concat([
        old_history,
        pd.DataFrame([{
            "date": forecast_date,
            "sales": prediction,
            "onpromotion": 0
        }])
    ], ignore_index=True)


debug_comparison = pd.DataFrame({
    "date": old_future_dates,
    "old_prediction": old_predictions,
    "new_prediction": test_forecast_df["predicted_sales"].values
})

debug_comparison["difference"] = (
    debug_comparison["old_prediction"]
    - debug_comparison["new_prediction"]
)

print(debug_comparison.to_string(index=False))

print("\nMaximum difference:",
      debug_comparison["difference"].abs().max())

print("First differing day:")

different = debug_comparison[
    debug_comparison["difference"].abs() > 0.0001
]

if len(different) > 0:
    print(different.iloc[0])
else:
    print("No differences")

      date  old_prediction  new_prediction  difference
2017-08-16     2469.128906     2469.128906         0.0
2017-08-17     2179.654297     2179.654297         0.0
2017-08-18     2338.447266     2338.447266         0.0
2017-08-19     2206.261719     2206.261719         0.0
2017-08-20      971.245972      971.245972         0.0
2017-08-21     2091.707520     2091.707520         0.0
2017-08-22     2322.104004     2322.104004         0.0
2017-08-23     2567.027344     2567.027344         0.0
2017-08-24     2130.554932     2130.554932         0.0
2017-08-25     2292.117920     2292.117920         0.0
2017-08-26     2180.121094     2180.121094         0.0
2017-08-27      947.027039      947.027039         0.0
2017-08-28     2041.621948     2041.621948         0.0
2017-08-29     2211.574707     2211.574707         0.0
2017-08-30     2666.200684     2666.200684         0.0
2017-08-31     2027.215698     2027.215698         0.0
2017-09-01     2569.500732     2569.500732         0.0
2017-09-02     2390.667480     2390.667480         0.0
2017-09-03     1079.781494     1079.781494         0.0
2017-09-04     2351.827393     2351.827393         0.0
2017-09-05     2400.162598     2400.162598         0.0
2017-09-06     2729.453613     2729.453613         0.0
2017-09-07     2260.536865     2260.536865         0.0
2017-09-08     2251.112549     2251.112549         0.0
2017-09-09     2066.737793     2066.737793         0.0
2017-09-10      965.755920      965.755920         0.0
2017-09-11     2193.904785     2193.904785         0.0
2017-09-12     2245.310547     2245.310547         0.0
2017-09-13     2635.095459     2635.095459         0.0
2017-09-14     2070.877930     2070.877930         0.0

Maximum difference: 0.0
First differing day:
No differences

In [41]:
LEAD_TIME_DAYS = 7
SERVICE_LEVEL_Z = 1.65

ORDERING_COST = 500
HOLDING_COST = 10

COMPLETE_YEARS = [2013, 2014, 2015, 2016]


def calculate_inventory_plan(forecast_df, model_df, store_nbr, family):
    """
    Calculate inventory planning metrics for one Store × Family.
    """

    # Forecast-based demand statistics
    daily_forecast_mean = forecast_df["predicted_sales"].mean()
    daily_forecast_std = forecast_df["predicted_sales"].std()

    lead_time_demand = (
        daily_forecast_mean * LEAD_TIME_DAYS
    )

    safety_stock = (
        SERVICE_LEVEL_Z
        * daily_forecast_std
        * np.sqrt(LEAD_TIME_DAYS)
    )

    reorder_point = (
        lead_time_demand + safety_stock
    )

    # Historical annual demand
    annual_demand = (
        model_df[
            model_df["date"].dt.year.isin(COMPLETE_YEARS)
        ]
        .groupby(model_df["date"].dt.year)["sales"]
        .sum()
    )

    average_annual_demand = annual_demand.mean()

    # EOQ
    eoq = np.sqrt(
        (
            2
            * average_annual_demand
            * ORDERING_COST
        )
        / HOLDING_COST
    )

    inventory_plan = pd.DataFrame([{
        "store_nbr": store_nbr,
        "family": family,
        "lead_time_days": LEAD_TIME_DAYS,
        "lead_time_demand": lead_time_demand,
        "safety_stock": safety_stock,
        "reorder_point": reorder_point,
        "eoq": eoq
    }])

    return inventory_plan

In [42]:
test_inventory_plan = calculate_inventory_plan(
    test_forecast_df,
    test_model_df,
    1,
    "GROCERY I"
)

print(test_inventory_plan.to_string(index=False))

 store_nbr    family  lead_time_days  lead_time_demand  safety_stock  reorder_point         eoq
         1 GROCERY I               7       14898.97168   2143.597918   17042.569598 8806.514634

In [43]:
def run_store_family_pipeline(sales_df, store_nbr, family):
    """
    Run the complete forecasting + inventory pipeline
    for one Store × Family combination.
    """

    # 1. Prepare data
    raw_df, model_df = prepare_store_family_data(
        sales_df,
        store_nbr,
        family
    )

    # 2. Train and evaluate
    model, train_df, test_df, predictions, metrics = train_and_evaluate(
        model_df
    )

    # 3. Train final model on all historical data
    final_model = train_final_model(model_df)

    # 4. Generate 30-day forecast
    forecast_df = generate_30_day_forecast(
        final_model,
        model_df
    )

    # 5. Calculate inventory plan
    inventory_df = calculate_inventory_plan(
        forecast_df,
        model_df,
        store_nbr,
        family
    )

    return {
        "raw_df": raw_df,
        "model_df": model_df,
        "model": model,
        "train_df": train_df,
        "test_df": test_df,
        "predictions": predictions,
        "metrics": metrics,
        "final_model": final_model,
        "forecast_df": forecast_df,
        "inventory_df": inventory_df
    }

In [44]:
test_pipeline = run_store_family_pipeline(
    sales_df,
    1,
    "GROCERY I"
)

print("Store:", 1)
print("Family:", "GROCERY I")

print("\nForecast rows:",
      len(test_pipeline["forecast_df"]))

print("Forecast total:",
      test_pipeline["forecast_df"]["predicted_sales"].sum())

print("MAE:",
      test_pipeline["metrics"]["mae"])

print("RMSE:",
      test_pipeline["metrics"]["rmse"])

print("\nInventory:")
print(
    test_pipeline["inventory_df"]
    .to_string(index=False)
)

Store: 1
Family: GROCERY I

Forecast rows: 30
Forecast total: 63852.74
MAE: 295.0883036295573
RMSE: 388.5083591995155

Inventory:
 store_nbr    family  lead_time_days  lead_time_demand  safety_stock  reorder_point         eoq
         1 GROCERY I               7       14898.97168   2143.597918   17042.569598 8806.514634

In [45]:
# ==============================
# CREATE PIPELINE RUN
# ==============================

def create_pipeline_run(store_nbr, family):
    run_timestamp = pd.Timestamp.now()
    
    data_cutoff_date = pd.to_datetime(sales_df["date"]).max()
    forecast_start_date = data_cutoff_date + pd.Timedelta(days=1)
    forecast_end_date = data_cutoff_date + pd.Timedelta(days=30)

    run_query = text("""
        INSERT INTO pipeline_runs (
            run_timestamp,
            data_cutoff_date,
            forecast_start_date,
            forecast_end_date,
            model_name,
            model_version
        )
        VALUES (
            :run_timestamp,
            :data_cutoff_date,
            :forecast_start_date,
            :forecast_end_date,
            :model_name,
            :model_version
        )
        RETURNING run_id;
    """)

    with engine.begin() as conn:
        run_id = conn.execute(
            run_query,
            {
                "run_timestamp": run_timestamp,
                "data_cutoff_date": data_cutoff_date,
                "forecast_start_date": forecast_start_date,
                "forecast_end_date": forecast_end_date,
                "model_name": "XGBoost",
                "model_version": "v2"
            }
        ).scalar()

    print(f"Created run_id={run_id} for Store {store_nbr} × {family}")

    return run_id

## Two-Pass Store × Family Execution

Each Store × Family combination is now processed in two independent forecasting passes:

1. **Pass 1 — Backtest:** train on N-30 and recursively forecast the last 30 actual days.
2. **Pass 2 — Future Forecast:** train on all available history and recursively forecast the next 30 days.

Each pass receives its own PostgreSQL-generated `run_id`, and each pass writes forecast, metrics, and inventory outputs.

In [46]:
# ============================================================
# BACKTEST RUN ID
# ============================================================

def create_backtest_run(data_cutoff_date,
                        forecast_start_date,
                        forecast_end_date):

    run_query = text("""
        INSERT INTO pipeline_runs (
            run_timestamp,
            data_cutoff_date,
            forecast_start_date,
            forecast_end_date,
            model_name,
            model_version
        )
        VALUES (
            :run_timestamp,
            :data_cutoff_date,
            :forecast_start_date,
            :forecast_end_date,
            :model_name,
            :model_version
        )
        RETURNING run_id;
    """)

    with engine.begin() as conn:
        run_id = conn.execute(
            run_query,
            {
                "run_timestamp": pd.Timestamp.now(),
                "data_cutoff_date": data_cutoff_date,
                "forecast_start_date": forecast_start_date,
                "forecast_end_date": forecast_end_date,
                "model_name": "XGBoost",
                "model_version": "v2_backtest_30d"
            }
        ).scalar()

    return run_id


print("Backtest run creator ready.")

Backtest run creator ready.

In [47]:
# ============================================================
# BACKTEST FORECAST
# Train on N-30 -> Forecast the final 30 actual dates
# ============================================================

def backtest_last_30_days(model_df):

    train_df = model_df.iloc[:-TEST_DAYS].copy()
    test_df = model_df.iloc[-TEST_DAYS:].copy()

    # Train ONLY on N-30 historical data.
    model = train_final_model(train_df)

    history = train_df[
        ["date", "sales", "onpromotion"]
    ].copy()

    predictions = []

    for _, test_row in test_df.iterrows():

        forecast_date = test_row["date"]

        # Keep the same future-promotion assumption used by
        # generate_30_day_forecast().
        onpromotion = 0

        X_future = pd.DataFrame([{
            "onpromotion": onpromotion,
            "year": forecast_date.year,
            "month": forecast_date.month,
            "day": forecast_date.day,
            "dayofweek": forecast_date.dayofweek,
            "dayofyear": forecast_date.dayofyear,
            "weekofyear": int(
                forecast_date.isocalendar().week
            ),
            "lag_1": history["sales"].iloc[-1],
            "lag_7": history["sales"].iloc[-7],
            "lag_14": history["sales"].iloc[-14],
            "lag_28": history["sales"].iloc[-28],
            "rolling_mean_7": history["sales"].iloc[-7:].mean(),
            "rolling_mean_14": history["sales"].iloc[-14:].mean(),
            "rolling_mean_28": history["sales"].iloc[-28:].mean()
        }])

        prediction = model.predict(X_future)[0]
        prediction = max(0, prediction)

        predictions.append(prediction)

        # Recursive update with the predicted value.
        history = pd.concat(
            [
                history,
                pd.DataFrame([{
                    "date": forecast_date,
                    "sales": prediction,
                    "onpromotion": onpromotion
                }])
            ],
            ignore_index=True
        )

    return pd.DataFrame({
        "forecast_date": test_df["date"].values,
        "predicted_sales": predictions
    })


print("Backtest forecast function ready.")

Backtest forecast function ready.

### Pass 1 — Backtest

For every Store × Family, the model is trained on `model_df.iloc[:-30]` and forecasts the final 30 actual dates. Metrics are calculated against the held-out `test_df`, and the same inventory-planning function is applied to the backtest forecast.

In [49]:
# ============================================================
# RUN BOTH PASSES FOR ALL STORE × FAMILY COMBINATIONS
# ============================================================

backtest_results = []
future_results = []

backtest_forecast_batch = []
backtest_metrics_batch = []
backtest_inventory_batch = []

future_forecast_batch = []
future_metrics_batch = []
future_inventory_batch = []

for store_nbr, family in DEV_COMBINATIONS:

    print(f"\nRunning Store {store_nbr} × {family}...")

    # Prepare data once for this Store × Family.
    raw_df, model_df = prepare_store_family_data(
        sales_df,
        store_nbr,
        family
    )

    if len(model_df) <= TEST_DAYS:
        raise ValueError(
            f"Insufficient data for Store {store_nbr} × {family}: "
            f"{len(model_df)} model-ready rows."
        )

    # --------------------------------------------------------
    # PASS 1: BACKTEST
    # --------------------------------------------------------

    print("\n--- PASS 1: BACKTEST ---")

    train_df = model_df.iloc[:-TEST_DAYS].copy()
    test_df = model_df.iloc[-TEST_DAYS:].copy()

    backtest_forecast_df = backtest_last_30_days(model_df)

    # Compare predictions with the actual final 30 sales values.
    actual_sales = test_df["sales"].to_numpy()
    predicted_sales = backtest_forecast_df["predicted_sales"].to_numpy()

    backtest_mae = mean_absolute_error(
        actual_sales,
        predicted_sales
    )

    backtest_rmse = np.sqrt(
        mean_squared_error(
            actual_sales,
            predicted_sales
        )
    )

    backtest_mae_pct = (
        (backtest_mae / test_df["sales"].mean()) * 100
    )

    backtest_metrics = {
        "mae": backtest_mae,
        "rmse": backtest_rmse,
        "mae_pct": backtest_mae_pct
    }

    backtest_inventory_df = calculate_inventory_plan(
        backtest_forecast_df,
        model_df,
        store_nbr,
        family
    )

    backtest_run_id = create_backtest_run(
        train_df["date"].max(),
        test_df["date"].min(),
        test_df["date"].max()
    )

    print(
        f"Created backtest run_id={backtest_run_id} | "
        f"Store {store_nbr} × {family}"
    )

    # Forecast batch
    temp_backtest_forecast = backtest_forecast_df.copy()
    temp_backtest_forecast["run_id"] = backtest_run_id
    temp_backtest_forecast["store_nbr"] = store_nbr
    temp_backtest_forecast["family"] = family
    temp_backtest_forecast["model_version"] = "v2_backtest_30d"

    temp_backtest_forecast = temp_backtest_forecast[
        [
            "run_id",
            "forecast_date",
            "store_nbr",
            "family",
            "predicted_sales"
        ]
    ]

    backtest_forecast_batch.append(temp_backtest_forecast)

    # Metrics batch
    backtest_metrics_batch.append({
        "run_id": backtest_run_id,
        "store_nbr": store_nbr,
        "family": family,
        "mae": backtest_metrics["mae"],
        "rmse": backtest_metrics["rmse"],
        "mae_pct": backtest_metrics["mae_pct"]
    })

    # Inventory batch
    temp_backtest_inventory = backtest_inventory_df.copy()
    temp_backtest_inventory["run_id"] = backtest_run_id

    temp_backtest_inventory = temp_backtest_inventory[
        [
            "run_id",
            "store_nbr",
            "family",
            "lead_time_days",
            "lead_time_demand",
            "safety_stock",
            "reorder_point",
            "eoq"
        ]
    ]

    backtest_inventory_batch.append(temp_backtest_inventory)

    backtest_results.append({
        "store_nbr": store_nbr,
        "family": family,
        "run_id": backtest_run_id,
        "train_df": train_df,
        "test_df": test_df,
        "forecast_df": backtest_forecast_df,
        "metrics": backtest_metrics,
        "inventory_df": backtest_inventory_df
    })

    print(
        "Backtest rows:",
        len(backtest_forecast_df),
        "| MAE:",
        round(backtest_mae, 4),
        "| RMSE:",
        round(backtest_rmse, 4)
    )

    # --------------------------------------------------------
    # PASS 2: FUTURE FORECAST
    # --------------------------------------------------------

    print("\n--- PASS 2: FUTURE FORECAST ---")

    result = run_store_family_pipeline(
        sales_df,
        store_nbr,
        family
    )

    # One independent future run_id for this Store × Family.
    future_run_id = create_pipeline_run(
        store_nbr,
        family
    )

    print(
        f"Created future run_id={future_run_id} | "
        f"Store {store_nbr} × {family}"
    )

    # Forecast batch
    temp_future_forecast = result["forecast_df"].copy()
    temp_future_forecast["run_id"] = future_run_id
    temp_future_forecast["store_nbr"] = store_nbr
    temp_future_forecast["family"] = family

    temp_future_forecast = temp_future_forecast[
        [
            "run_id",
            "forecast_date",
            "store_nbr",
            "family",
            "predicted_sales"
        ]
    ]

    future_forecast_batch.append(temp_future_forecast)

    # Metrics batch
    future_metrics_batch.append({
        "run_id": future_run_id,
        "store_nbr": store_nbr,
        "family": family,
        "mae": result["metrics"]["mae"],
        "rmse": result["metrics"]["rmse"],
        "mae_pct": result["metrics"]["mae_pct"]
    })

    # Inventory batch
    temp_future_inventory = result["inventory_df"].copy()
    temp_future_inventory["run_id"] = future_run_id

    temp_future_inventory = temp_future_inventory[
        [
            "run_id",
            "store_nbr",
            "family",
            "lead_time_days",
            "lead_time_demand",
            "safety_stock",
            "reorder_point",
            "eoq"
        ]
    ]

    future_inventory_batch.append(temp_future_inventory)

    future_results.append({
        "store_nbr": store_nbr,
        "family": family,
        "run_id": future_run_id,
        "result": result
    })

    print(
        "Future forecast rows:",
        len(result["forecast_df"]),
        "| MAE:",
        round(result["metrics"]["mae"], 4),
        "| RMSE:",
        round(result["metrics"]["rmse"], 4)
    )


print("\n====================================")
print("TWO-PASS EXECUTION COMPLETED")
print("====================================")
print("Completed combinations:", len(DEV_COMBINATIONS))
print("Backtest run IDs:", len(backtest_results))
print("Future run IDs:", len(future_results))
print("Total new run IDs:", len(backtest_results) + len(future_results))

Running Store 1 × BEVERAGES...

--- PASS 1: BACKTEST ---
Created backtest run_id=3 | Store 1 × BEVERAGES
Backtest rows: 30 | MAE: 596.9764 | RMSE: 682.1396

--- PASS 2: FUTURE FORECAST ---
Created run_id=4 for Store 1 × BEVERAGES
Created future run_id=4 | Store 1 × BEVERAGES
Future forecast rows: 30 | MAE: 233.3911 | RMSE: 322.7866

Running Store 1 × CLEANING...

--- PASS 1: BACKTEST ---
Created backtest run_id=5 | Store 1 × CLEANING
Backtest rows: 30 | MAE: 81.8039 | RMSE: 118.6388

--- PASS 2: FUTURE FORECAST ---
Created run_id=6 for Store 1 × CLEANING
Created future run_id=6 | Store 1 × CLEANING
Future forecast rows: 30 | MAE: 88.2807 | RMSE: 128.1423

Running Store 1 × DAIRY...

--- PASS 1: BACKTEST ---
Created backtest run_id=7 | Store 1 × DAIRY
Backtest rows: 30 | MAE: 62.3284 | RMSE: 90.8619

--- PASS 2: FUTURE FORECAST ---
Created run_id=8 for Store 1 × DAIRY
Created future run_id=8 | Store 1 × DAIRY
Future forecast rows: 30 | MAE: 71.4233 | RMSE: 103.7061

Running Store 1 × GROCERY I...

--- PASS 1: BACKTEST ---
Created backtest run_id=9 | Store 1 × GROCERY I
Backtest rows: 30 | MAE: 334.2064 | RMSE: 416.3662

--- PASS 2: FUTURE FORECAST ---
Created run_id=10 for Store 1 × GROCERY I
Created future run_id=10 | Store 1 × GROCERY I
Future forecast rows: 30 | MAE: 295.0883 | RMSE: 388.5084

Running Store 1 × PRODUCE...

--- PASS 1: BACKTEST ---
Created backtest run_id=11 | Store 1 × PRODUCE
Backtest rows: 30 | MAE: 363.6516 | RMSE: 599.4192

--- PASS 2: FUTURE FORECAST ---
Created run_id=12 for Store 1 × PRODUCE
Created future run_id=12 | Store 1 × PRODUCE
Future forecast rows: 30 | MAE: 174.908 | RMSE: 278.0466

Running Store 2 × BEVERAGES...

--- PASS 1: BACKTEST ---
Created backtest run_id=13 | Store 2 × BEVERAGES
Backtest rows: 30 | MAE: 712.6509 | RMSE: 798.4507

--- PASS 2: FUTURE FORECAST ---
Created run_id=14 for Store 2 × BEVERAGES
Created future run_id=14 | Store 2 × BEVERAGES
Future forecast rows: 30 | MAE: 320.4938 | RMSE: 393.216

Running Store 2 × CLEANING...

--- PASS 1: BACKTEST ---
Created backtest run_id=15 | Store 2 × CLEANING
Backtest rows: 30 | MAE: 103.8622 | RMSE: 132.4992

--- PASS 2: FUTURE FORECAST ---
Created run_id=16 for Store 2 × CLEANING
Created future run_id=16 | Store 2 × CLEANING
Future forecast rows: 30 | MAE: 85.1923 | RMSE: 106.7103

Running Store 2 × DAIRY...

--- PASS 1: BACKTEST ---
Created backtest run_id=17 | Store 2 × DAIRY
Backtest rows: 30 | MAE: 73.852 | RMSE: 97.1659

--- PASS 2: FUTURE FORECAST ---
Created run_id=18 for Store 2 × DAIRY
Created future run_id=18 | Store 2 × DAIRY
Future forecast rows: 30 | MAE: 75.6647 | RMSE: 89.0393

Running Store 2 × GROCERY I...

--- PASS 1: BACKTEST ---
Created backtest run_id=19 | Store 2 × GROCERY I
Backtest rows: 30 | MAE: 437.6966 | RMSE: 528.0299

--- PASS 2: FUTURE FORECAST ---
Created run_id=20 for Store 2 × GROCERY I
Created future run_id=20 | Store 2 × GROCERY I
Future forecast rows: 30 | MAE: 248.106 | RMSE: 311.2022

Running Store 2 × PRODUCE...

--- PASS 1: BACKTEST ---
Created backtest run_id=21 | Store 2 × PRODUCE
Backtest rows: 30 | MAE: 208.9165 | RMSE: 265.9058

--- PASS 2: FUTURE FORECAST ---
Created run_id=22 for Store 2 × PRODUCE
Created future run_id=22 | Store 2 × PRODUCE
Future forecast rows: 30 | MAE: 155.4516 | RMSE: 186.0695

Running Store 3 × BEVERAGES...

--- PASS 1: BACKTEST ---
Created backtest run_id=23 | Store 3 × BEVERAGES
Backtest rows: 30 | MAE: 1062.5658 | RMSE: 1300.8985

--- PASS 2: FUTURE FORECAST ---
Created run_id=24 for Store 3 × BEVERAGES
Created future run_id=24 | Store 3 × BEVERAGES
Future forecast rows: 30 | MAE: 889.9765 | RMSE: 1137.115

Running Store 3 × CLEANING...

--- PASS 1: BACKTEST ---
Created backtest run_id=25 | Store 3 × CLEANING
Backtest rows: 30 | MAE: 231.5124 | RMSE: 297.1488

--- PASS 2: FUTURE FORECAST ---
Created run_id=26 for Store 3 × CLEANING
Created future run_id=26 | Store 3 × CLEANING
Future forecast rows: 30 | MAE: 220.613 | RMSE: 279.7164

Running Store 3 × DAIRY...

--- PASS 1: BACKTEST ---
Created backtest run_id=27 | Store 3 × DAIRY
Backtest rows: 30 | MAE: 82.3398 | RMSE: 102.188

--- PASS 2: FUTURE FORECAST ---
Created run_id=28 for Store 3 × DAIRY
Created future run_id=28 | Store 3 × DAIRY
Future forecast rows: 30 | MAE: 82.7558 | RMSE: 99.5524

Running Store 3 × GROCERY I...

--- PASS 1: BACKTEST ---
Created backtest run_id=29 | Store 3 × GROCERY I
Backtest rows: 30 | MAE: 610.4869 | RMSE: 855.3858

--- PASS 2: FUTURE FORECAST ---
Created run_id=30 for Store 3 × GROCERY I
Created future run_id=30 | Store 3 × GROCERY I
Future forecast rows: 30 | MAE: 577.0126 | RMSE: 804.6012

Running Store 3 × PRODUCE...

--- PASS 1: BACKTEST ---
Created backtest run_id=31 | Store 3 × PRODUCE
Backtest rows: 30 | MAE: 658.0378 | RMSE: 954.9789

--- PASS 2: FUTURE FORECAST ---
Created run_id=32 for Store 3 × PRODUCE
Created future run_id=32 | Store 3 × PRODUCE
Future forecast rows: 30 | MAE: 386.239 | RMSE: 456.9436

Running Store 4 × BEVERAGES...

--- PASS 1: BACKTEST ---
Created backtest run_id=33 | Store 4 × BEVERAGES
Backtest rows: 30 | MAE: 779.0793 | RMSE: 895.4212

--- PASS 2: FUTURE FORECAST ---
Created run_id=34 for Store 4 × BEVERAGES
Created future run_id=34 | Store 4 × BEVERAGES
Future forecast rows: 30 | MAE: 280.158 | RMSE: 356.0816

Running Store 4 × CLEANING...

--- PASS 1: BACKTEST ---
Created backtest run_id=35 | Store 4 × CLEANING
Backtest rows: 30 | MAE: 106.1812 | RMSE: 142.0942

--- PASS 2: FUTURE FORECAST ---
Created run_id=36 for Store 4 × CLEANING
Created future run_id=36 | Store 4 × CLEANING
Future forecast rows: 30 | MAE: 106.3136 | RMSE: 138.7108

Running Store 4 × DAIRY...

--- PASS 1: BACKTEST ---
Created backtest run_id=37 | Store 4 × DAIRY
Backtest rows: 30 | MAE: 56.3529 | RMSE: 73.2558

--- PASS 2: FUTURE FORECAST ---
Created run_id=38 for Store 4 × DAIRY
Created future run_id=38 | Store 4 × DAIRY
Future forecast rows: 30 | MAE: 60.8196 | RMSE: 75.5987

Running Store 4 × GROCERY I...

--- PASS 1: BACKTEST ---
Created backtest run_id=39 | Store 4 × GROCERY I
Backtest rows: 30 | MAE: 350.703 | RMSE: 459.9236

--- PASS 2: FUTURE FORECAST ---
Created run_id=40 for Store 4 × GROCERY I
Created future run_id=40 | Store 4 × GROCERY I
Future forecast rows: 30 | MAE: 330.003 | RMSE: 437.1658

Running Store 4 × PRODUCE...

--- PASS 1: BACKTEST ---
Created backtest run_id=41 | Store 4 × PRODUCE
Backtest rows: 30 | MAE: 173.8579 | RMSE: 232.4453

--- PASS 2: FUTURE FORECAST ---
Created run_id=42 for Store 4 × PRODUCE
Created future run_id=42 | Store 4 × PRODUCE
Future forecast rows: 30 | MAE: 159.4679 | RMSE: 215.5694

Running Store 5 × BEVERAGES...

--- PASS 1: BACKTEST ---
Created backtest run_id=43 | Store 5 × BEVERAGES
Backtest rows: 30 | MAE: 338.4618 | RMSE: 439.0905

--- PASS 2: FUTURE FORECAST ---
Created run_id=44 for Store 5 × BEVERAGES
Created future run_id=44 | Store 5 × BEVERAGES
Future forecast rows: 30 | MAE: 229.3538 | RMSE: 332.0039

Running Store 5 × CLEANING...

--- PASS 1: BACKTEST ---
Created backtest run_id=45 | Store 5 × CLEANING
Backtest rows: 30 | MAE: 150.6715 | RMSE: 202.1712

--- PASS 2: FUTURE FORECAST ---
Created run_id=46 for Store 5 × CLEANING
Created future run_id=46 | Store 5 × CLEANING
Future forecast rows: 30 | MAE: 130.7076 | RMSE: 163.3694

Running Store 5 × DAIRY...

--- PASS 1: BACKTEST ---
Created backtest run_id=47 | Store 5 × DAIRY
Backtest rows: 30 | MAE: 49.3306 | RMSE: 64.7642

--- PASS 2: FUTURE FORECAST ---
Created run_id=48 for Store 5 × DAIRY
Created future run_id=48 | Store 5 × DAIRY
Future forecast rows: 30 | MAE: 40.259 | RMSE: 57.4177

Running Store 5 × GROCERY I...

--- PASS 1: BACKTEST ---
Created backtest run_id=49 | Store 5 × GROCERY I
Backtest rows: 30 | MAE: 254.2467 | RMSE: 308.5742

--- PASS 2: FUTURE FORECAST ---
Created run_id=50 for Store 5 × GROCERY I
Created future run_id=50 | Store 5 × GROCERY I
Future forecast rows: 30 | MAE: 243.7984 | RMSE: 305.3026

Running Store 5 × PRODUCE...

--- PASS 1: BACKTEST ---
Created backtest run_id=51 | Store 5 × PRODUCE
Backtest rows: 30 | MAE: 163.3202 | RMSE: 223.9979

--- PASS 2: FUTURE FORECAST ---
Created run_id=52 for Store 5 × PRODUCE
Created future run_id=52 | Store 5 × PRODUCE
Future forecast rows: 30 | MAE: 105.127 | RMSE: 128.1804

====================================
TWO-PASS EXECUTION COMPLETED
====================================
Completed combinations: 25
Backtest run IDs: 25
Future run IDs: 25
Total new run IDs: 50

In [50]:
# ============================================================
# ASSEMBLE BATCH OUTPUTS
# ============================================================

backtest_forecast_batch_df = pd.concat(
    backtest_forecast_batch,
    ignore_index=True
)

backtest_metrics_batch_df = pd.DataFrame(
    backtest_metrics_batch
)

backtest_inventory_batch_df = pd.concat(
    backtest_inventory_batch,
    ignore_index=True
)

future_forecast_batch_df = pd.concat(
    future_forecast_batch,
    ignore_index=True
)

future_metrics_batch_df = pd.DataFrame(
    future_metrics_batch
)

future_inventory_batch_df = pd.concat(
    future_inventory_batch,
    ignore_index=True
)

print("BACKTEST BATCH")
print("Forecast batch shape:", backtest_forecast_batch_df.shape)
print("Metrics batch shape:", backtest_metrics_batch_df.shape)
print("Inventory batch shape:", backtest_inventory_batch_df.shape)

print("\nFUTURE BATCH")
print("Forecast batch shape:", future_forecast_batch_df.shape)
print("Metrics batch shape:", future_metrics_batch_df.shape)
print("Inventory batch shape:", future_inventory_batch_df.shape)

print("\nUnique Run IDs:")
print(
    "Backtest:",
    backtest_forecast_batch_df["run_id"].nunique()
)
print(
    "Future:",
    future_forecast_batch_df["run_id"].nunique()
)

BACKTEST BATCH
Forecast batch shape: (750, 5)
Metrics batch shape: (25, 6)
Inventory batch shape: (25, 8)

FUTURE BATCH
Forecast batch shape: (750, 5)
Metrics batch shape: (25, 6)
Inventory batch shape: (25, 8)

Unique Run IDs:
Backtest: 25
Future: 25

In [51]:
# ============================================================
# BATCH VALIDATION
# ============================================================

print("Expected combinations:", len(DEV_COMBINATIONS))

# Each pass: 25 combinations × 30 forecast days = 750 rows.
assert len(backtest_forecast_batch_df) == 750
assert len(backtest_metrics_batch_df) == 25
assert len(backtest_inventory_batch_df) == 25

assert len(future_forecast_batch_df) == 750
assert len(future_metrics_batch_df) == 25
assert len(future_inventory_batch_df) == 25

# Exactly one run_id per Store × Family within each pass.
assert (
    backtest_forecast_batch_df
    .groupby(["store_nbr", "family"])["run_id"]
    .nunique()
    .eq(1)
    .all()
)

assert (
    backtest_metrics_batch_df
    .groupby(["store_nbr", "family"])["run_id"]
    .nunique()
    .eq(1)
    .all()
)

assert (
    backtest_inventory_batch_df
    .groupby(["store_nbr", "family"])["run_id"]
    .nunique()
    .eq(1)
    .all()
)

assert (
    future_forecast_batch_df
    .groupby(["store_nbr", "family"])["run_id"]
    .nunique()
    .eq(1)
    .all()
)

assert (
    future_metrics_batch_df
    .groupby(["store_nbr", "family"])["run_id"]
    .nunique()
    .eq(1)
    .all()
)

assert (
    future_inventory_batch_df
    .groupby(["store_nbr", "family"])["run_id"]
    .nunique()
    .eq(1)
    .all()
)

# Each pass must have 25 distinct run IDs.
assert backtest_forecast_batch_df["run_id"].nunique() == 25
assert backtest_metrics_batch_df["run_id"].nunique() == 25
assert backtest_inventory_batch_df["run_id"].nunique() == 25

assert future_forecast_batch_df["run_id"].nunique() == 25
assert future_metrics_batch_df["run_id"].nunique() == 25
assert future_inventory_batch_df["run_id"].nunique() == 25

# Backtest and future run IDs must be completely distinct.
assert (
    set(backtest_forecast_batch_df["run_id"])
    .isdisjoint(
        set(future_forecast_batch_df["run_id"])
    )
)

# No nulls.
assert backtest_forecast_batch_df.isnull().sum().sum() == 0
assert backtest_metrics_batch_df.isnull().sum().sum() == 0
assert backtest_inventory_batch_df.isnull().sum().sum() == 0

assert future_forecast_batch_df.isnull().sum().sum() == 0
assert future_metrics_batch_df.isnull().sum().sum() == 0
assert future_inventory_batch_df.isnull().sum().sum() == 0

# Store × Family coverage.
assert (
    backtest_forecast_batch_df[
        ["store_nbr", "family"]
    ].drop_duplicates().shape[0] == 25
)

assert (
    backtest_metrics_batch_df[
        ["store_nbr", "family"]
    ].drop_duplicates().shape[0] == 25
)

assert (
    backtest_inventory_batch_df[
        ["store_nbr", "family"]
    ].drop_duplicates().shape[0] == 25
)

assert (
    future_forecast_batch_df[
        ["store_nbr", "family"]
    ].drop_duplicates().shape[0] == 25
)

assert (
    future_metrics_batch_df[
        ["store_nbr", "family"]
    ].drop_duplicates().shape[0] == 25
)

assert (
    future_inventory_batch_df[
        ["store_nbr", "family"]
    ].drop_duplicates().shape[0] == 25
)

# Forecast date validation.
for df in [backtest_forecast_batch_df, future_forecast_batch_df]:
    date_check = (
        df.groupby(["store_nbr", "family"])
        .agg(
            rows=("forecast_date", "size"),
            unique_dates=("forecast_date", "nunique")
        )
    )

    assert date_check["rows"].eq(30).all()
    assert date_check["unique_dates"].eq(30).all()

print("BATCH VALIDATION PASSED")

print("\nBacktest:")
print(
    "Forecast rows:", len(backtest_forecast_batch_df)
)
print(
    "Metrics rows:", len(backtest_metrics_batch_df)
)
print(
    "Inventory rows:", len(backtest_inventory_batch_df)
)

print("\nFuture:")
print(
    "Forecast rows:", len(future_forecast_batch_df)
)
print(
    "Metrics rows:", len(future_metrics_batch_df)
)
print(
    "Inventory rows:", len(future_inventory_batch_df)
)

print("\nTotal new run IDs:",
      backtest_forecast_batch_df["run_id"].nunique()
      + future_forecast_batch_df["run_id"].nunique())

Expected combinations: 25
BATCH VALIDATION PASSED

Backtest:
Forecast rows: 750
Metrics rows: 25
Inventory rows: 25

Future:
Forecast rows: 750
Metrics rows: 25
Inventory rows: 25

Total new run IDs: 50

## Run ID Usage

`run_id` is generated by PostgreSQL using the `pipeline_runs` identity/sequence mechanism. The notebook does not manually calculate or increment the ID.

For every Store × Family:
- the backtest pass receives one `v2_backtest_30d` run_id;
- the future pass receives one `v2` run_id.

The returned IDs are reused for the corresponding forecast, metrics, and inventory records.

In [52]:
# ============================================================
# PREPARE DATA FOR SQL
# ============================================================

backtest_forecast_sql_df = backtest_forecast_batch_df.copy()
backtest_metrics_sql_df = backtest_metrics_batch_df.copy()
backtest_inventory_sql_df = backtest_inventory_batch_df.copy()

future_forecast_sql_df = future_forecast_batch_df.copy()
future_metrics_sql_df = future_metrics_batch_df.copy()
future_inventory_sql_df = future_inventory_batch_df.copy()

print("BACKTEST SQL SHAPES")
print("Forecast SQL shape:", backtest_forecast_sql_df.shape)
print("Metrics SQL shape:", backtest_metrics_sql_df.shape)
print("Inventory SQL shape:", backtest_inventory_sql_df.shape)

print("\nFUTURE SQL SHAPES")
print("Forecast SQL shape:", future_forecast_sql_df.shape)
print("Metrics SQL shape:", future_metrics_sql_df.shape)
print("Inventory SQL shape:", future_inventory_sql_df.shape)

BACKTEST SQL SHAPES
Forecast SQL shape: (750, 5)
Metrics SQL shape: (25, 6)
Inventory SQL shape: (25, 8)

FUTURE SQL SHAPES
Forecast SQL shape: (750, 5)
Metrics SQL shape: (25, 6)
Inventory SQL shape: (25, 8)

In [53]:
# ============================================================
# PRE-SQL VALIDATION
# ============================================================

# Backtest: 25 Store × Family combinations.
assert len(DEV_COMBINATIONS) == 25
assert len(backtest_forecast_sql_df) == 750
assert len(backtest_metrics_sql_df) == 25
assert len(backtest_inventory_sql_df) == 25

# Future: 25 Store × Family combinations.
assert len(future_forecast_sql_df) == 750
assert len(future_metrics_sql_df) == 25
assert len(future_inventory_sql_df) == 25

# Same run_id mapping within each pass.
for forecast_df, metrics_df, inventory_df in [
    (
        backtest_forecast_sql_df,
        backtest_metrics_sql_df,
        backtest_inventory_sql_df
    ),
    (
        future_forecast_sql_df,
        future_metrics_sql_df,
        future_inventory_sql_df
    )
]:
    forecast_map = (
        forecast_df[
            ["run_id", "store_nbr", "family"]
        ]
        .drop_duplicates()
        .sort_values(["store_nbr", "family"])
        .reset_index(drop=True)
    )

    metrics_map = (
        metrics_df[
            ["run_id", "store_nbr", "family"]
        ]
        .drop_duplicates()
        .sort_values(["store_nbr", "family"])
        .reset_index(drop=True)
    )

    inventory_map = (
        inventory_df[
            ["run_id", "store_nbr", "family"]
        ]
        .drop_duplicates()
        .sort_values(["store_nbr", "family"])
        .reset_index(drop=True)
    )

    assert forecast_map.equals(metrics_map)
    assert forecast_map.equals(inventory_map)
    assert forecast_map["run_id"].nunique() == 25

# Backtest and future mappings use distinct run IDs.
assert (
    set(backtest_forecast_sql_df["run_id"])
    .isdisjoint(
        set(future_forecast_sql_df["run_id"])
    )
)

# No nulls.
for df in [
    backtest_forecast_sql_df,
    backtest_metrics_sql_df,
    backtest_inventory_sql_df,
    future_forecast_sql_df,
    future_metrics_sql_df,
    future_inventory_sql_df
]:
    assert df.isnull().sum().sum() == 0

print("PRE-SQL VALIDATION PASSED")

print("\nBacktest run ID mapping:")
print(
    backtest_forecast_sql_df[
        ["run_id", "store_nbr", "family"]
    ]
    .drop_duplicates()
    .sort_values("run_id")
    .to_string(index=False)
)

print("\nFuture run ID mapping:")
print(
    future_forecast_sql_df[
        ["run_id", "store_nbr", "family"]
    ]
    .drop_duplicates()
    .sort_values("run_id")
    .to_string(index=False)
)

PRE-SQL VALIDATION PASSED

Backtest run ID mapping:
 run_id  store_nbr    family
      3          1 BEVERAGES
      5          1  CLEANING
      7          1     DAIRY
      9          1 GROCERY I
     11          1   PRODUCE
     13          2 BEVERAGES
     15          2  CLEANING
     17          2     DAIRY
     19          2 GROCERY I
     21          2   PRODUCE
     23          3 BEVERAGES
     25          3  CLEANING
     27          3     DAIRY
     29          3 GROCERY I
     31          3   PRODUCE
     33          4 BEVERAGES
     35          4  CLEANING
     37          4     DAIRY
     39          4 GROCERY I
     41          4   PRODUCE
     43          5 BEVERAGES
     45          5  CLEANING
     47          5     DAIRY
     49          5 GROCERY I
     51          5   PRODUCE

Future run ID mapping:
 run_id  store_nbr    family
      4          1 BEVERAGES
      6          1  CLEANING
      8          1     DAIRY
     10          1 GROCERY I
     12          1   PRODUCE
     14          2 BEVERAGES
     16          2  CLEANING
     18          2     DAIRY
     20          2 GROCERY I
     22          2   PRODUCE
     24          3 BEVERAGES
     26          3  CLEANING
     28          3     DAIRY
     30          3 GROCERY I
     32          3   PRODUCE
     34          4 BEVERAGES
     36          4  CLEANING
     38          4     DAIRY
     40          4 GROCERY I
     42          4   PRODUCE
     44          5 BEVERAGES
     46          5  CLEANING
     48          5     DAIRY
     50          5 GROCERY I
     52          5   PRODUCE

## Pass 1 SQL Write — Backtest

The complete backtest batch is written in one database transaction. Forecast, metrics, and inventory rows all use the backtest `run_id` for their Store × Family combination.

In [54]:
# ============================================================
# WRITE BACKTEST BATCH TO SQL
# ============================================================

with engine.begin() as conn:

    backtest_forecast_sql_df.to_sql(
        "forecast",
        conn,
        schema="public",
        if_exists="append",
        index=False,
        method="multi"
    )

    backtest_metrics_sql_df.to_sql(
        "forecast_metrics",
        conn,
        schema="public",
        if_exists="append",
        index=False,
        method="multi"
    )

    backtest_inventory_sql_df.to_sql(
        "inventory_plan",
        conn,
        schema="public",
        if_exists="append",
        index=False,
        method="multi"
    )

print("BACKTEST SQL WRITE COMPLETED")
print("Run IDs:", backtest_forecast_sql_df["run_id"].nunique())
print("Forecast rows written:", len(backtest_forecast_sql_df))
print("Metrics rows written:", len(backtest_metrics_sql_df))
print("Inventory rows written:", len(backtest_inventory_sql_df))

BACKTEST SQL WRITE COMPLETED
Run IDs: 25
Forecast rows written: 750
Metrics rows written: 25
Inventory rows written: 25

In [55]:
# ============================================================
# FINAL SQL VALIDATION — BACKTEST
# ============================================================

backtest_run_ids = tuple(
    backtest_forecast_sql_df["run_id"].unique().tolist()
)

sql_validation_backtest = pd.read_sql(
    text("""
        SELECT
            pr.run_id,
            pr.data_cutoff_date,
            pr.forecast_start_date,
            pr.forecast_end_date,
            pr.model_name,
            pr.model_version,

            COUNT(DISTINCT f.forecast_id) AS forecast_rows,
            COUNT(DISTINCT fm.metric_id) AS metric_rows,
            COUNT(DISTINCT ip.inventory_plan_id) AS inventory_rows,

            COUNT(DISTINCT
                f.store_nbr::text || '|' || f.family
            ) AS forecast_combinations,

            COUNT(DISTINCT
                fm.store_nbr::text || '|' || fm.family
            ) AS metric_combinations,

            COUNT(DISTINCT
                ip.store_nbr::text || '|' || ip.family
            ) AS inventory_combinations,

            MIN(f.forecast_date) AS actual_forecast_min,
            MAX(f.forecast_date) AS actual_forecast_max,

            SUM(
                CASE
                    WHEN f.predicted_sales < 0 THEN 1
                    ELSE 0
                END
            ) AS negative_forecasts,

            SUM(
                CASE
                    WHEN f.predicted_sales IS NULL THEN 1
                    ELSE 0
                END
            ) AS null_forecasts

        FROM public.pipeline_runs pr

        LEFT JOIN public.forecast f
            ON pr.run_id = f.run_id

        LEFT JOIN public.forecast_metrics fm
            ON pr.run_id = fm.run_id

        LEFT JOIN public.inventory_plan ip
            ON pr.run_id = ip.run_id

        WHERE pr.run_id IN :run_ids

        GROUP BY
            pr.run_id,
            pr.data_cutoff_date,
            pr.forecast_start_date,
            pr.forecast_end_date,
            pr.model_name,
            pr.model_version

        ORDER BY pr.run_id;
    """).bindparams(
        __import__("sqlalchemy").bindparam(
            "run_ids",
            expanding=True
        )
    ),
    engine,
    params={"run_ids": list(backtest_run_ids)}
)

print("BACKTEST SQL VALIDATION:")
print(sql_validation_backtest.to_string(index=False))

assert len(sql_validation_backtest) == 25
assert sql_validation_backtest["model_version"].eq(
    "v2_backtest_30d"
).all()
assert sql_validation_backtest["forecast_rows"].eq(30).all()
assert sql_validation_backtest["metric_rows"].eq(1).all()
assert sql_validation_backtest["inventory_rows"].eq(1).all()
assert sql_validation_backtest["forecast_combinations"].eq(1).all()
assert sql_validation_backtest["metric_combinations"].eq(1).all()
assert sql_validation_backtest["inventory_combinations"].eq(1).all()
assert sql_validation_backtest["negative_forecasts"].fillna(0).eq(0).all()
assert sql_validation_backtest["null_forecasts"].fillna(0).eq(0).all()

print("BACKTEST FINAL SQL VALIDATION PASSED")

BACKTEST SQL VALIDATION:
 run_id data_cutoff_date forecast_start_date forecast_end_date model_name   model_version  forecast_rows  metric_rows  inventory_rows  forecast_combinations  metric_combinations  inventory_combinations actual_forecast_min actual_forecast_max  negative_forecasts  null_forecasts
      3       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
      5       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
      7       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
      9       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     11       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     13       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     15       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     17       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     19       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     21       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     23       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     25       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     27       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     29       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     31       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     33       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     35       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     37       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     39       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     41       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     43       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     45       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     47       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     49       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
     51       2017-07-16          2017-07-17        2017-08-15    XGBoost v2_backtest_30d             30            1               1                      1                    1                       1          2017-07-17          2017-08-15                   0               0
BACKTEST FINAL SQL VALIDATION PASSED

In [56]:
# ============================================================
# DATE VALIDATION — BACKTEST
# ============================================================

backtest_date_validation = pd.read_sql(
    text("""
        SELECT
            store_nbr,
            family,
            COUNT(*) AS forecast_rows,
            MIN(forecast_date) AS min_date,
            MAX(forecast_date) AS max_date,
            COUNT(DISTINCT forecast_date) AS unique_dates
        FROM public.forecast
        WHERE run_id IN :run_ids
        GROUP BY store_nbr, family
        ORDER BY store_nbr, family;
    """).bindparams(
        __import__("sqlalchemy").bindparam(
            "run_ids",
            expanding=True
        )
    ),
    engine,
    params={"run_ids": list(backtest_run_ids)}
)

print(backtest_date_validation.to_string(index=False))

print("\nCombinations:", len(backtest_date_validation))
print(
    "Incorrect row counts:",
    (backtest_date_validation["forecast_rows"] != 30).sum()
)
print(
    "Incorrect unique dates:",
    (backtest_date_validation["unique_dates"] != 30).sum()
)

assert len(backtest_date_validation) == 25
assert backtest_date_validation["forecast_rows"].eq(30).all()
assert backtest_date_validation["unique_dates"].eq(30).all()

print("BACKTEST DATE VALIDATION PASSED")

 store_nbr    family  forecast_rows   min_date   max_date  unique_dates
         1 BEVERAGES             30 2017-07-17 2017-08-15            30
         1  CLEANING             30 2017-07-17 2017-08-15            30
         1     DAIRY             30 2017-07-17 2017-08-15            30
         1 GROCERY I             30 2017-07-17 2017-08-15            30
         1   PRODUCE             30 2017-07-17 2017-08-15            30
         2 BEVERAGES             30 2017-07-17 2017-08-15            30
         2  CLEANING             30 2017-07-17 2017-08-15            30
         2     DAIRY             30 2017-07-17 2017-08-15            30
         2 GROCERY I             30 2017-07-17 2017-08-15            30
         2   PRODUCE             30 2017-07-17 2017-08-15            30
         3 BEVERAGES             30 2017-07-17 2017-08-15            30
         3  CLEANING             30 2017-07-17 2017-08-15            30
         3     DAIRY             30 2017-07-17 2017-08-15            30
         3 GROCERY I             30 2017-07-17 2017-08-15            30
         3   PRODUCE             30 2017-07-17 2017-08-15            30
         4 BEVERAGES             30 2017-07-17 2017-08-15            30
         4  CLEANING             30 2017-07-17 2017-08-15            30
         4     DAIRY             30 2017-07-17 2017-08-15            30
         4 GROCERY I             30 2017-07-17 2017-08-15            30
         4   PRODUCE             30 2017-07-17 2017-08-15            30
         5 BEVERAGES             30 2017-07-17 2017-08-15            30
         5  CLEANING             30 2017-07-17 2017-08-15            30
         5     DAIRY             30 2017-07-17 2017-08-15            30
         5 GROCERY I             30 2017-07-17 2017-08-15            30
         5   PRODUCE             30 2017-07-17 2017-08-15            30

Combinations: 25
Incorrect row counts: 0
Incorrect unique dates: 0
BACKTEST DATE VALIDATION PASSED

## Pass 2 SQL Write — Future Forecast

The complete future-forecast batch is written in a separate database transaction, again covering forecast, metrics, and inventory.

In [57]:
# ============================================================
# WRITE FUTURE BATCH TO SQL
# ============================================================

with engine.begin() as conn:

    future_forecast_sql_df.to_sql(
        "forecast",
        conn,
        schema="public",
        if_exists="append",
        index=False,
        method="multi"
    )

    future_metrics_sql_df.to_sql(
        "forecast_metrics",
        conn,
        schema="public",
        if_exists="append",
        index=False,
        method="multi"
    )

    future_inventory_sql_df.to_sql(
        "inventory_plan",
        conn,
        schema="public",
        if_exists="append",
        index=False,
        method="multi"
    )

print("FUTURE SQL WRITE COMPLETED")
print("Run IDs:", future_forecast_sql_df["run_id"].nunique())
print("Forecast rows written:", len(future_forecast_sql_df))
print("Metrics rows written:", len(future_metrics_sql_df))
print("Inventory rows written:", len(future_inventory_sql_df))

FUTURE SQL WRITE COMPLETED
Run IDs: 25
Forecast rows written: 750
Metrics rows written: 25
Inventory rows written: 25

In [58]:
# ============================================================
# FINAL SQL VALIDATION — FUTURE
# ============================================================

future_run_ids = tuple(
    future_forecast_sql_df["run_id"].unique().tolist()
)

sql_validation_future = pd.read_sql(
    text("""
        SELECT
            pr.run_id,
            pr.data_cutoff_date,
            pr.forecast_start_date,
            pr.forecast_end_date,
            pr.model_name,
            pr.model_version,

            COUNT(DISTINCT f.forecast_id) AS forecast_rows,
            COUNT(DISTINCT fm.metric_id) AS metric_rows,
            COUNT(DISTINCT ip.inventory_plan_id) AS inventory_rows,

            COUNT(DISTINCT
                f.store_nbr::text || '|' || f.family
            ) AS forecast_combinations,

            COUNT(DISTINCT
                fm.store_nbr::text || '|' || fm.family
            ) AS metric_combinations,

            COUNT(DISTINCT
                ip.store_nbr::text || '|' || ip.family
            ) AS inventory_combinations,

            MIN(f.forecast_date) AS actual_forecast_min,
            MAX(f.forecast_date) AS actual_forecast_max,

            SUM(
                CASE
                    WHEN f.predicted_sales < 0 THEN 1
                    ELSE 0
                END
            ) AS negative_forecasts,

            SUM(
                CASE
                    WHEN f.predicted_sales IS NULL THEN 1
                    ELSE 0
                END
            ) AS null_forecasts

        FROM public.pipeline_runs pr

        LEFT JOIN public.forecast f
            ON pr.run_id = f.run_id

        LEFT JOIN public.forecast_metrics fm
            ON pr.run_id = fm.run_id

        LEFT JOIN public.inventory_plan ip
            ON pr.run_id = ip.run_id

        WHERE pr.run_id IN :run_ids

        GROUP BY
            pr.run_id,
            pr.data_cutoff_date,
            pr.forecast_start_date,
            pr.forecast_end_date,
            pr.model_name,
            pr.model_version

        ORDER BY pr.run_id;
    """).bindparams(
        __import__("sqlalchemy").bindparam(
            "run_ids",
            expanding=True
        )
    ),
    engine,
    params={"run_ids": list(future_run_ids)}
)

print("FUTURE SQL VALIDATION:")
print(sql_validation_future.to_string(index=False))

assert len(sql_validation_future) == 25
assert sql_validation_future["model_version"].eq("v2").all()
assert sql_validation_future["forecast_rows"].eq(30).all()
assert sql_validation_future["metric_rows"].eq(1).all()
assert sql_validation_future["inventory_rows"].eq(1).all()
assert sql_validation_future["forecast_combinations"].eq(1).all()
assert sql_validation_future["metric_combinations"].eq(1).all()
assert sql_validation_future["inventory_combinations"].eq(1).all()
assert sql_validation_future["negative_forecasts"].fillna(0).eq(0).all()
assert sql_validation_future["null_forecasts"].fillna(0).eq(0).all()

print("FUTURE FINAL SQL VALIDATION PASSED")

FUTURE SQL VALIDATION:
 run_id data_cutoff_date forecast_start_date forecast_end_date model_name model_version  forecast_rows  metric_rows  inventory_rows  forecast_combinations  metric_combinations  inventory_combinations actual_forecast_min actual_forecast_max  negative_forecasts  null_forecasts
      4       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
      6       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
      8       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     10       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     12       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     14       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     16       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     18       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     20       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     22       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     24       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     26       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     28       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     30       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     32       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     34       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     36       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     38       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     40       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     42       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     44       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     46       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     48       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     50       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
     52       2017-08-15          2017-08-16        2017-09-14    XGBoost            v2             30            1               1                      1                    1                       1          2017-08-16          2017-09-14                   0               0
FUTURE FINAL SQL VALIDATION PASSED

In [59]:
# ============================================================
# DATE VALIDATION — FUTURE
# ============================================================

future_date_validation = pd.read_sql(
    text("""
        SELECT
            store_nbr,
            family,
            COUNT(*) AS forecast_rows,
            MIN(forecast_date) AS min_date,
            MAX(forecast_date) AS max_date,
            COUNT(DISTINCT forecast_date) AS unique_dates
        FROM public.forecast
        WHERE run_id IN :run_ids
        GROUP BY store_nbr, family
        ORDER BY store_nbr, family;
    """).bindparams(
        __import__("sqlalchemy").bindparam(
            "run_ids",
            expanding=True
        )
    ),
    engine,
    params={"run_ids": list(future_run_ids)}
)

print(future_date_validation.to_string(index=False))

print("\nCombinations:", len(future_date_validation))
print(
    "Incorrect row counts:",
    (future_date_validation["forecast_rows"] != 30).sum()
)
print(
    "Incorrect unique dates:",
    (future_date_validation["unique_dates"] != 30).sum()
)

assert len(future_date_validation) == 25
assert future_date_validation["forecast_rows"].eq(30).all()
assert future_date_validation["unique_dates"].eq(30).all()

print("FUTURE DATE VALIDATION PASSED")

 store_nbr    family  forecast_rows   min_date   max_date  unique_dates
         1 BEVERAGES             30 2017-08-16 2017-09-14            30
         1  CLEANING             30 2017-08-16 2017-09-14            30
         1     DAIRY             30 2017-08-16 2017-09-14            30
         1 GROCERY I             30 2017-08-16 2017-09-14            30
         1   PRODUCE             30 2017-08-16 2017-09-14            30
         2 BEVERAGES             30 2017-08-16 2017-09-14            30
         2  CLEANING             30 2017-08-16 2017-09-14            30
         2     DAIRY             30 2017-08-16 2017-09-14            30
         2 GROCERY I             30 2017-08-16 2017-09-14            30
         2   PRODUCE             30 2017-08-16 2017-09-14            30
         3 BEVERAGES             30 2017-08-16 2017-09-14            30
         3  CLEANING             30 2017-08-16 2017-09-14            30
         3     DAIRY             30 2017-08-16 2017-09-14            30
         3 GROCERY I             30 2017-08-16 2017-09-14            30
         3   PRODUCE             30 2017-08-16 2017-09-14            30
         4 BEVERAGES             30 2017-08-16 2017-09-14            30
         4  CLEANING             30 2017-08-16 2017-09-14            30
         4     DAIRY             30 2017-08-16 2017-09-14            30
         4 GROCERY I             30 2017-08-16 2017-09-14            30
         4   PRODUCE             30 2017-08-16 2017-09-14            30
         5 BEVERAGES             30 2017-08-16 2017-09-14            30
         5  CLEANING             30 2017-08-16 2017-09-14            30
         5     DAIRY             30 2017-08-16 2017-09-14            30
         5 GROCERY I             30 2017-08-16 2017-09-14            30
         5   PRODUCE             30 2017-08-16 2017-09-14            30

Combinations: 25
Incorrect row counts: 0
Incorrect unique dates: 0
FUTURE DATE VALIDATION PASSED

In [60]:
# ============================================================
# FINAL TWO-PASS SUMMARY
# ============================================================

print("====================================")
print("FINAL TWO-PASS PIPELINE SUMMARY")
print("====================================")

print("\nBacktest:")
print("  Model version:", "v2_backtest_30d")
print("  Run IDs:", backtest_forecast_sql_df["run_id"].nunique())
print("  Forecast rows:", len(backtest_forecast_sql_df))
print("  Metrics rows:", len(backtest_metrics_sql_df))
print("  Inventory rows:", len(backtest_inventory_sql_df))

print("\nFuture:")
print("  Model version:", "v2")
print("  Run IDs:", future_forecast_sql_df["run_id"].nunique())
print("  Forecast rows:", len(future_forecast_sql_df))
print("  Metrics rows:", len(future_metrics_sql_df))
print("  Inventory rows:", len(future_inventory_sql_df))

print("\nTotal new run IDs:",
      backtest_forecast_sql_df["run_id"].nunique()
      + future_forecast_sql_df["run_id"].nunique())

assert (
    backtest_forecast_sql_df["run_id"].nunique()
    + future_forecast_sql_df["run_id"].nunique()
    == 50
)

print("\nALL TWO-PASS VALIDATIONS PASSED")

====================================
FINAL TWO-PASS PIPELINE SUMMARY
====================================

Backtest:
  Model version: v2_backtest_30d
  Run IDs: 25
  Forecast rows: 750
  Metrics rows: 25
  Inventory rows: 25

Future:
  Model version: v2
  Run IDs: 25
  Forecast rows: 750
  Metrics rows: 25
  Inventory rows: 25

Total new run IDs: 50

ALL TWO-PASS VALIDATIONS PASSED